(()=>{'use strict';
let pdfJsPromise=null;
const text=v=>String(v??'').replace(/\s+/g,' ').trim();
async function loadPdfJs(){if(window.pdfjsLib)return window.pdfjsLib;if(!pdfJsPromise)pdfJsPromise=import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs').then(lib=>{lib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';window.pdfjsLib=lib;return lib}).catch(e=>{pdfJsPromise=null;throw e});return pdfJsPromise}
async function readPdfLines(file){const lib=await loadPdfJs();const data=new Uint8Array(await file.arrayBuffer());const pdf=await lib.getDocument({data}).promise;const lines=[];for(let p=1;p<=pdf.numPages;p++){const page=await pdf.getPage(p),content=await page.getTextContent(),rows=new Map();for(const it of content.items){const y=Math.round(Number(it.transform?.[5]||0)*2)/2;if(!rows.has(y))rows.set(y,[]);rows.get(y).push(it)}[...rows.entries()].sort((a,b)=>b[0]-a[0]).forEach(([,items])=>{const line=items.sort((a,b)=>Number(a.transform?.[4]||0)-Number(b.transform?.[4]||0)).map(x=>x.str).join(' ').replace(/\s+/g,' ').trim();if(line)lines.push(line)})}return lines}
function detectSource(lines){const s=lines.join(' ');if((/Nationellt resultatintyg/i.test(s)&&/Avslutade kurser/i.test(s))||(/Resultatintyg/i.test(s)&&(/student\.ladok\.se\/verifiera/i.test(s)||/utdrag ur registret för studiedokumentation/i.test(s))))return'ladok';if(/Antagning\.se/i.test(s)&&/Universitet och högskola/i.test(s))return'antagning';return'unknown'}
function guessSubject(name){const n=text(name).toLowerCase();if(/folkhälso|epidemiologi|public health/.test(n))return'Folkhälsovetenskap';if(/psykolog|psycholog/.test(n))return'Psykologi';if(/företagsekonomi|marknadsföring/.test(n))return'Företagsekonomi';if(/idrott|träningslära|fysisk aktivitet|hälsopromotion/.test(n))return'Idrottsvetenskap';if(/sociolog/.test(n))return'Sociologi';return''}
function cleanName(v){return text(v).replace(/\s+(?:Nationellt resultatintyg|Utskriftsdatum|Personnummer|Sida \d).*$/i,'').trim()}
function parseLadokLines(raw){const lines=raw.map(text).filter(Boolean),isLadok=detectSource(lines)==='ladok';let institution='Okänt lärosäte',inCourses=false,out=[];const instLine=l=>!(/Resultatintyg över högre utbildning|svenska universitet|Ladok/i.test(l))&&l.length<100&&/(universitet|högskol)/i.test(l);const candidates=lines.filter(instLine);if(candidates.length)institution=candidates[candidates.length-1];const row=/^([A-ZÅÄÖ0-9][A-ZÅÄÖ0-9.\-]{2,15})\s+(.+?)\s+(\d+(?:[,.]\d+)?)\s*hp\s+([A-ZÅÄÖ0-9+\-]+)\s+(\d{4}-\d{2}-\d{2})(?:\s+\d+)?$/i;const ignore=l=>/^(Summering|Totalt|varav tillgodoräknat|Noter och information|Kontrollera intyget|Kontrollkod|Sida \d|Kod Benämning|Kod$|Benämning$|Omfattning$|Betyg$|Datum$|Not$|Utfärdade bevis|Titel|Huvudområde:)/i.test(l)||/Nationellt resultatintyg|Utskriftsdatum|Personnummer/i.test(l)||/\b\d{8}-\d{4}\b/.test(l);for(const l of lines){if(instLine(l))institution=l;if(/^Avslutade kurser$/i.test(l)){inCourses=true;continue}if(/^Delar i ej avslutade kurser$|^Summering$/i.test(l)){inCourses=false;continue}if(!inCourses)continue;const m=l.match(row);if(m){const name=cleanName(m[2]);out.push({institution,code:m[1].toUpperCase(),name,hp:Number(m[3].replace(',','.')),grade:m[4],date:m[5],subject:guessSubject(name),thesis:/kandidatuppsats|examensarbete|självständigt arbete|thesis/i.test(name),source:'Ladok'});continue}if(out.length&&!ignore(l)&&!/\d+(?:[,.]\d+)?\s*hp/i.test(l)&&l.length<100){const prev=out[out.length-1];if(prev.institution===institution){prev.name=cleanName(prev.name+' '+l);prev.subject=guessSubject(prev.name);prev.thesis=/kandidatuppsats|examensarbete|självständigt arbete|thesis/i.test(prev.name)}}}const seen=new Set();out=out.filter(c=>{const k=[c.institution,c.code,c.name,c.hp,c.date].join('|').toLowerCase();if(seen.has(k))return false;seen.add(k);return true});return{isLadok,courses:out,expectedTotal:out.reduce((s,c)=>s+c.hp,0)}}
async function parseFile(file){const lines=await readPdfLines(file),source=detectSource(lines);if(source!=='ladok')throw new Error(source==='antagning'?'Det här ser ut som en PDF från Antagning.se. Välj Antagning.se-fliken.':'PDF:en känns inte igen som ett Ladok-resultatintyg.');const result=parseLadokLines(lines);if(!result.courses.length)throw new Error('PDF:en kunde läsas, men inga avslutade kurser hittades.');return result}
window.StudieLotsV2=window.StudieLotsV2||{};window.StudieLotsV2.ladok=Object.freeze({readPdfLines,detectSource,parseLadokLines,parseFile});
})();