(()=>{
const VERSION='604';
const nameOf=r=>String(r?.name??r?.courseName??r?.title??r?.course??'').trim();
function style(){if(document.getElementById('studielots-v604-style'))return;const s=document.createElement('style');s.id='studielots-v604-style';s.textContent=`#plannerClean .sl-change-wrap{margin-top:8px;display:grid;gap:5px}.sl-change-badge{display:inline-flex;align-items:center;width:max-content;max-width:100%;padding:4px 8px;border-radius:999px;font-size:11px;font-weight:800}.sl-change-badge.credited{background:#eaf6f1;color:#155f57}.sl-change-badge.moved{background:#eef3ff;color:#315db5}.sl-change-copy{font-size:11px;line-height:1.4;color:#6d7776}.sl-change-copy strong{color:#334846}#plannerClean .sl-course-credited{background:linear-gradient(0deg,rgba(234,246,241,.42),rgba(234,246,241,.42)),#fff!important;border-color:rgba(21,95,87,.18)!important}#plannerClean .sl-course-moved{border-color:rgba(49,93,181,.20)!important}`;document.head.appendChild(s)}
function wrapBuilder(){const cur=window.__studielotsBuildProgramSchedule;if(typeof cur!=='function'||cur.__sl604)return;const base=cur;const fn=function(snapshot){const out=base.apply(this,arguments);if(out&&typeof out==='object'){window.__studielotsLastProgramSchedule=out;queueMicrotask(decorate)}return out};fn.__sl604=true;fn.__slBase=base;window.__studielotsBuildProgramSchedule=fn}
function candidateNodes(root){return Array.from(root.querySelectorAll('[data-course-name],.v572-course,.v572-row,.course-card,.course,.study-item,.analysis-row,.course-row'))}
function bestNode(root,name){if(!name)return null;const lc=name.toLowerCase();const direct=root.querySelector(`[data-course-name="${CSS.escape(name)}"]`);if(direct)return direct;const matches=candidateNodes(root).filter(el=>{const t=(el.textContent||'').toLowerCase();return t.includes(lc)});if(!matches.length)return null;matches.sort((a,b)=>(a.textContent||'').length-(b.textContent||'').length);return matches[0]}
function addChange(node,row){if(!node||node.querySelector(':scope > .sl-change-wrap'))return;const wrap=document.createElement('div');wrap.className='sl-change-wrap';if(row.credited){node.classList.add('sl-course-credited');const b=document.createElement('div');b.className='sl-change-badge credited';b.textContent='✓ Tillgodoräknad';wrap.appendChild(b);const copy=document.createElement('div');copy.className='sl-change-copy';copy.textContent=row.suggestedAlternative?`Frigjord plats: förslag att läsa ${row.suggestedAlternative} i stället.`:'Kursen ligger kvar för jämförelse. Den frigjorda platsen kan användas för en alternativ eller tidigarelagd kurs.';wrap.appendChild(copy)}else if(row.movedEarlier){node.classList.add('sl-course-moved');const b=document.createElement('div');b.className='sl-change-badge moved';b.textContent='↗ Tidigarelagd';wrap.appendChild(b);const copy=document.createElement('div');copy.className='sl-change-copy';copy.textContent=`Flyttad från termin ${row.originalTerm} till termin ${row.plannedTerm} i Snabbare väg.`;wrap.appendChild(copy)}if(wrap.children.length)node.appendChild(wrap)}
function decorate(){style();const root=document.querySelector('#plannerClean');const schedule=window.__studielotsLastProgramSchedule;if(!root||!schedule||!Array.isArray(schedule.rows))return;schedule.rows.filter(r=>r.credited||r.movedEarlier).forEach(r=>addChange(bestNode(root,nameOf(r)),r));root.dataset.fasterRouteChanges='visible'}
function install(){style();wrapBuilder();decorate();document.documentElement.dataset.studielotsPatch=VERSION;window.__studielotsLatestPatch={...(window.__studielotsLatestPatch||{}),version:VERSION,plannerChangeAnnotations:true,plannerPreservesCreditedCourses:true}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(install,0));else setTimeout(install,0);
let tries=0;const timer=setInterval(()=>{install();if(++tries>80)clearInterval(timer)},250);
new MutationObserver(()=>decorate()).observe(document.documentElement,{subtree:true,childList:true});
window.addEventListener('studielots:pacechange',()=>setTimeout(decorate,0));
})();