(()=>{
const VERSION='602',PACE_KEY='studielots_planner_pace_hp';
const paceValues=[30,37.5,45];
const hp=n=>Math.round((Number(n)||0)*2)/2;
const fmt=n=>String(hp(n)).replace('.',',');
const getPace=()=>{const n=Number(localStorage.getItem(PACE_KEY));return paceValues.includes(n)?n:30};
function policy(){const pace=getPace();const p={version:VERSION,baseline:'program-schedule',scheduleSource:'program-term-rows',maxHpPerTerm:pace,respectPrerequisites:true,respectOfferingPeriod:true,fasterRouteOptIn:pace>30};window.__studielotsPlannerPolicy=p;window.__studielotsPlannerMaxHp=pace;window.__studielotsBuild={...(window.__studielotsBuild||{}),maxPlannedHpPerTerm:pace,plannerPaceSelectable:true,plannerScheduleSource:'program-schedule',legacyPlannerGuard:true};return p}
function setPace(n){n=Number(n);if(!paceValues.includes(n))n=30;localStorage.setItem(PACE_KEY,String(n));policy();window.dispatchEvent(new CustomEvent('studielots:pacechange',{detail:{maxHpPerTerm:n,baseline:'program-schedule'}}));window.dispatchEvent(new CustomEvent('studielots:planner-policy-change',{detail:window.__studielotsPlannerPolicy}));ensurePacePicker()}
function ensureStyle(){if(document.getElementById('studielots-v602-style'))return;const s=document.createElement('style');s.id='studielots-v602-style';s.textContent=`#sl-pace-picker{margin:12px 0 16px;padding:14px;border-radius:18px;background:#fff;border:1px solid rgba(15,76,67,.10);box-shadow:0 4px 16px rgba(15,76,67,.05)}#sl-pace-picker .sl-pace-title{font-weight:800;font-size:15px;margin-bottom:3px;color:#113d3a}#sl-pace-picker .sl-pace-sub{font-size:12px;color:#74807f;margin-bottom:10px}#sl-pace-picker .sl-pace-options{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}#sl-pace-picker button{appearance:none;border:1px solid rgba(15,76,67,.16);background:#f6f8f7;color:#155f57;border-radius:14px;padding:10px 5px;font-weight:800;font-size:13px}#sl-pace-picker button.active{background:#155f57;color:#fff;border-color:#155f57}#sl-pace-picker .sl-pace-note{font-size:11px;color:#74807f;margin-top:9px;line-height:1.35}.sl-fast-path-note{margin:8px 0 14px;padding:10px 12px;border-radius:14px;background:#f4f8f7;color:#155f57;font-size:12px;line-height:1.4}#plannerClean .v572-term-section[data-term-section="0"],#plannerClean .v572-term[data-term="0"]{display:none!important}`;document.head.appendChild(s)}
function ensurePacePicker(){const root=document.querySelector('#plannerClean');if(!root)return;ensureStyle();let box=document.getElementById('sl-pace-picker');if(!box){box=document.createElement('div');box.id='sl-pace-picker';box.innerHTML='<div class="sl-pace-title">Studietakt</div><div class="sl-pace-sub">Planen utgår från programmets ordinarie schema. Välj högsta studietakt per termin.</div><div class="sl-pace-options"><button data-pace="30">30 hp</button><button data-pace="37.5">37,5 hp</button><button data-pace="45">45 hp</button></div><div class="sl-pace-note">30 hp följer normal heltidsfart. Högre takt är frivillig och används bara när kursordning, förkunskapskrav och kurstillfällen tillåter det.</div>';box.addEventListener('click',e=>{const b=e.target.closest('button[data-pace]');if(b)setPace(b.dataset.pace)});const shell=root.querySelector('.v572-shell')||root.firstElementChild;root.insertBefore(box,shell||null)}const pace=getPace();box.querySelectorAll('[data-pace]').forEach(b=>b.classList.toggle('active',Number(b.dataset.pace)===pace));let note=root.querySelector('.sl-fast-path-note');if(pace>30){if(!note){note=document.createElement('div');note.className='sl-fast-path-note';box.insertAdjacentElement('afterend',note)}note.textContent='Snabbare väg vald: upp till '+fmt(pace)+' hp/termin. StudieLots ska bara lägga till eller tidigarelägga kurser när det faktiskt kan korta examen utan att bryta programmets schema.'}else if(note)note.remove()}
function authoritativeRows(snapshot){const rows=Array.isArray(snapshot?.rows)?snapshot.rows:[];return rows.slice().sort((a,b)=>(Number(a.term)||999)-(Number(b.term)||999)||(Number(a.period)||999)-(Number(b.period)||999))}
window.__studielotsBuildProgramSchedule=function(snapshot){const p=policy(),rows=authoritativeRows(snapshot);return{...snapshot,rows,plannerPolicy:p,scheduleSource:'program-term-rows'}};
function v21Authority(o){try{if(!o||typeof window.universityOptionsForOpportunity!=='function')return null;const rows=window.universityOptionsForOpportunity(o);if(!Array.isArray(rows)||!rows.length)return null;const valid=rows.map(r=>({remaining:Number(r?.v2?.remaining??r?.remaining),row:r})).filter(x=>Number.isFinite(x.remaining)).sort((a,b)=>a.remaining-b.remaining);if(!valid.length)return null;const remaining=hp(valid[0].remaining),total=Number(o?.total||o?.totalHp||(o?.source==='advanced'?(String(o?.degreeType||'').toLowerCase()==='magister'?60:120):180));return{remaining,credited:hp(total-remaining)}}catch(e){return null}}
function wrap(name,maker){const cur=window[name];if(typeof cur!=='function'||cur.__sl602)return;const base=cur.__slBase||cur;const fn=maker(base);fn.__sl602=true;fn.__slBase=base;window[name]=fn}
function normalizeCalc(){wrap('safeDegreeOpportunities',base=>function(){const rows=base.apply(this,arguments);return Array.isArray(rows)?rows.map(o=>{const a=v21Authority(o);return a?{...o,remaining:a.remaining,credited:a.credited}:o}):rows});wrap('canonicalRemaining',base=>function(o){const a=v21Authority(o);return a?a.remaining:base.apply(this,arguments)});wrap('opportunityRemainingLabel',base=>function(o){const a=v21Authority(o);return a?(a.remaining?fmt(a.remaining)+' hp kvar':'Klar'):base.apply(this,arguments)})}
function guardLegacyPlanner(){if(window.__sl602PlannerGuard)return;const legacy=window.openStudyPlanner;if(typeof legacy!=='function')return;window.__sl602LegacyOpenStudyPlanner=legacy;window.openStudyPlanner=function(){if(typeof window.go==='function')window.go('plannerClean');requestAnimationFrame(()=>{window.dispatchEvent(new CustomEvent('studielots:planner-open',{detail:policy()}));document.dispatchEvent(new CustomEvent('studielots:screen-rendered',{detail:{screen:'plannerClean'}}));requestAnimationFrame(()=>{const host=document.querySelector('#plannerCleanContent');if(host&&!host.children.length){try{legacy.apply(this,arguments)}catch(e){}}ensurePacePicker()})})};window.openStudyPlanner.__sl602=true;window.__sl602PlannerGuard=true}
function sync(){policy();normalizeCalc();guardLegacyPlanner();ensurePacePicker();document.documentElement.dataset.studielotsPatch=VERSION}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(sync,0));else setTimeout(sync,0);
let tries=0;const t=setInterval(()=>{sync();if(++tries>60)clearInterval(t)},250);
new MutationObserver(()=>ensurePacePicker()).observe(document.documentElement,{subtree:true,childList:true});
window.__studielotsLatestPatch={version:VERSION,plannerPace:paceValues,plannerBaseline:'program-schedule',legacyPlannerGuard:true};
})();