const STUDIELOTS_PATCH='2026-09-01-m';
self.addEventListener('install',()=>self.skipWaiting());
self.addEventListener('activate',e=>e.waitUntil(self.clients.claim()));
const latestPatch=`
<style id="studielots-latest-patch">
.lotsen-bottomnav,.v341-bottomnav,.v444-bottomnav{bottom:max(5px,env(safe-area-inset-bottom,0px))!important;width:min(680px,calc(100% - 18px))!important;padding:4px 5px!important;border-radius:27px!important;background:rgba(249,249,246,.70)!important;-webkit-backdrop-filter:blur(20px) saturate(145%)!important;backdrop-filter:blur(20px) saturate(145%)!important;border:1px solid rgba(255,255,255,.72)!important;box-shadow:0 7px 24px rgba(16,24,40,.12)!important}.lotsen-bottomnav button,.v341-bottomnav button,.v444-bottomnav button{padding:5px 2px 4px!important;min-height:48px!important;border-radius:21px!important}.lotsen-bottomnav b,.v341-bottomnav b,.v444-bottomnav b{font-size:10px!important}.main{padding-bottom:calc(78px + env(safe-area-inset-bottom,0px))!important}@media(max-width:700px){.v21-detail{overflow:hidden!important}.v21-detail-top{display:block!important}.v21-back,.v21-score{display:none!important}.v21-detail-title{width:100%!important;padding:0!important}.v21-detail-title h1{overflow-wrap:anywhere!important}#opportunityAnalysisModal .course-row,#opportunityAnalysisModal .analysis-row,.v21-detail .course-row,.v21-detail .analysis-row{display:grid!important;grid-template-columns:minmax(0,1fr) auto!important;gap:10px!important;align-items:start!important;width:100%!important}#opportunityAnalysisModal .course-row>*,#opportunityAnalysisModal .analysis-row>*,.v21-detail .course-row>*,.v21-detail .analysis-row>*{min-width:0!important;width:auto!important;max-width:none!important}#opportunityAnalysisModal .course-row>*:first-child,#opportunityAnalysisModal .analysis-row>*:first-child,.v21-detail .course-row>*:first-child,.v21-detail .analysis-row>*:first-child{overflow-wrap:normal!important;word-break:normal!important;white-space:normal!important}#opportunityAnalysisModal .course-row>*:last-child,#opportunityAnalysisModal .analysis-row>*:last-child,.v21-detail .course-row>*:last-child,.v21-detail .analysis-row>*:last-child{white-space:nowrap!important;text-align:right!important}}
#plannerClean .v572-shell.sl-terms-collapsed .v572-studyplan{display:none!important}#plannerClean .v572-term-section[data-term-section="0"],#plannerClean .v572-term[data-term="0"]{display:none!important}
</style>
<script id="studielots-latest-patch-js">
(()=>{
const VERSION='600';
const hp=n=>Math.round((Number(n)||0)*2)/2,fmt=n=>String(hp(n)).replace('.',',');
function v21Authority(o){try{if(!o||typeof window.universityOptionsForOpportunity!=='function')return null;const rows=window.universityOptionsForOpportunity(o);if(!Array.isArray(rows)||!rows.length)return null;const valid=rows.map(r=>({remaining:Number(r?.v2?.remaining??r?.remaining),row:r})).filter(x=>Number.isFinite(x.remaining)).sort((a,b)=>a.remaining-b.remaining);if(!valid.length)return null;const remaining=hp(valid[0].remaining),total=Number(o?.total||o?.totalHp||(o?.source==='advanced'?(String(o?.degreeType||'').toLowerCase()==='magister'?60:120):180));return{remaining,credited:hp(total-remaining),row:valid[0].row}}catch(e){return null}}
function normalizeOpportunity(o){if(!o||typeof o!=='object')return o;const a=v21Authority(o);if(!a)return o;return{...o,remaining:a.remaining,credited:a.credited,score:Math.max(0,Math.min(100,Math.round(100*a.credited/Math.max(1,a.credited+a.remaining))))}}
function wrapSafe(){const cur=window.safeDegreeOpportunities;if(typeof cur!=='function'||cur.__sl600)return;const base=cur.__slBase||cur;const fn=function(){const rows=base.apply(this,arguments);return Array.isArray(rows)?rows.map(normalizeOpportunity):rows};fn.__sl600=true;fn.__slBase=base;window.safeDegreeOpportunities=fn}
function wrapCalc(name,maker){const cur=window[name];if(typeof cur!=='function'||cur.__sl600)return;const base=cur.__slBase||cur;const fn=maker(base);fn.__sl600=true;fn.__slBase=base;window[name]=fn}
function install(){wrapSafe();wrapCalc('canonicalRemaining',base=>function(o){const a=v21Authority(o);return a?a.remaining:base.apply(this,arguments)});wrapCalc('opportunityRemainingLabel',base=>function(o){const a=v21Authority(o);return a?(a.remaining?fmt(a.remaining)+' hp kvar':'Klar'):base.apply(this,arguments)});wrapCalc('opportunityStatus',base=>function(o){const a=v21Authority(o);return a?(a.remaining?fmt(a.remaining)+' hp kvar':'Klar'):base.apply(this,arguments)});document.documentElement.dataset.studielotsPatch=VERSION}
function fixBreakdownLayout(){document.querySelectorAll('body *').forEach(el=>{if(el.children.length<2)return;const t=(el.innerText||'').trim();if(!(/successiv fördjupning/i.test(t)||/Resterande\s+90\s+hp/i.test(t)))return;const r=el.getBoundingClientRect();if(r.width>0&&r.width<260){el.style.width='100%';el.style.maxWidth='none';el.style.minWidth='0';el.style.display='grid';el.style.gridTemplateColumns='minmax(0,1fr) auto';el.style.columnGap='12px';Array.from(el.children).forEach((c,i)=>{c.style.minWidth='0';c.style.width='auto';c.style.maxWidth='none';if(i===el.children.length-1){c.style.whiteSpace='nowrap';c.style.textAlign='right'}})}})}
function rerender(){install();fixBreakdownLayout();try{if(typeof window.renderDegrees==='function'&&document.querySelector('#opportunities.active,#opportunities.screen.active'))window.renderDegrees()}catch(e){}try{if(typeof window.renderHomeFastest==='function')window.renderHomeFastest()}catch(e){}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(rerender,0));else setTimeout(rerender,0);
let tries=0;const timer=setInterval(()=>{install();fixBreakdownLayout();if(++tries>40)clearInterval(timer)},250);
window.__studielotsLatestPatch={version:VERSION,patch:'2026-09-01-m',hpSource:'safeDegreeOpportunities-v2.1-normalized',mobileBreakdown:true};
})();
<\/script>`;
self.addEventListener('fetch',event=>{const u=new URL(event.request.url);if(u.pathname==='/share-ladok'&&event.request.method==='POST'){event.respondWith((async()=>{try{const form=await event.request.formData(),file=form.get('ladokPdf');if(!file)return Response.redirect('/?studielots-share-error=1',303);const c=await caches.open('studielots-share-v1');await c.put('/__studielots_shared_pdf__',new Response(file,{headers:{'content-type':file.type||'application/pdf','x-studielots-filename':file.name||'Ladok-resultatintyg.pdf'}}));return Response.redirect('/?studielots-share=1',303)}catch(e){return Response.redirect('/?studielots-share-error=1',303)}})());return}if(event.request.mode==='navigate'&&event.request.method==='GET'&&u.origin===self.location.origin){event.respondWith((async()=>{try{const response=await fetch(event.request,{cache:'no-store'}),type=response.headers.get('content-type')||'';if(!type.includes('text/html'))return response;let html=await response.text();html=html.replace(/<style id="studielots-latest-patch">[\\s\\S]*?<\\/script>/g,'').replace('</body>',latestPatch+'\\n</body>');const headers=new Headers(response.headers);headers.delete('content-length');headers.set('cache-control','no-store, max-age=0');headers.set('x-studielots-patch',STUDIELOTS_PATCH);return new Response(html,{status:response.status,statusText:response.statusText,headers})}catch(e){return fetch(event.request)}})())}});