const STUDIELOTS_PATCH='2026-09-01-j';
self.addEventListener('install',()=>self.skipWaiting());
self.addEventListener('activate',e=>e.waitUntil(self.clients.claim()));
const latestPatch=`
<style id="studielots-latest-patch">
.lotsen-bottomnav,.v341-bottomnav,.v444-bottomnav{bottom:max(5px,env(safe-area-inset-bottom,0px))!important;width:min(680px,calc(100% - 18px))!important;padding:4px 5px!important;border-radius:27px!important;background:rgba(249,249,246,.70)!important;-webkit-backdrop-filter:blur(20px) saturate(145%)!important;backdrop-filter:blur(20px) saturate(145%)!important;border:1px solid rgba(255,255,255,.72)!important;box-shadow:0 7px 24px rgba(16,24,40,.12)!important}.lotsen-bottomnav button,.v341-bottomnav button,.v444-bottomnav button{padding:5px 2px 4px!important;min-height:48px!important;border-radius:21px!important}.lotsen-bottomnav b,.v341-bottomnav b,.v444-bottomnav b{font-size:10px!important}.main{padding-bottom:calc(78px + env(safe-area-inset-bottom,0px))!important}@media(max-width:700px){.v21-detail{overflow:hidden!important}.v21-detail-top{display:block!important}.v21-back,.v21-score{display:none!important}.v21-detail-title{width:100%!important;padding:0!important}.v21-detail-title h1{overflow-wrap:anywhere!important}}#plannerClean .v572-shell.sl-terms-collapsed .v572-studyplan{display:none!important}#plannerClean .v572-term-section[data-term-section="0"],#plannerClean .v572-term[data-term="0"]{display:none!important}
</style>
<script id="studielots-latest-patch-js">
(()=>{
const VERSION='597';
const hp=n=>Math.round((Number(n)||0)*2)/2,fmt=n=>String(hp(n)).replace('.',',');
const norm=s=>String(s||'').toLocaleLowerCase('sv-SE').normalize('NFD').replace(/[\\u0300-\\u036f]/g,'').replace(/[^a-z0-9åäö]+/g,' ').trim();
const key=s=>norm(s).replace(/kandidatexamen|kandidat|examen/g,'').trim();
function read(){try{return JSON.parse(localStorage.getItem('studielots_verified_hp')||'{}')}catch(e){return{}}}
function save(subject,credited,remaining,source){if(!subject||!Number.isFinite(Number(remaining)))return;const all=read();all[key(subject)]={subject,credited:hp(credited),remaining:hp(remaining),source,ts:Date.now()};localStorage.setItem('studielots_verified_hp',JSON.stringify(all))}
function get(subject){return read()[key(subject)]||null}
function subjectFromText(t){const m=String(t||'').match(/(?:kandidatexamen(?:\\s+i)?|^|\\n)\\s*(Psykologi|Sociologi|Företagsekonomi|Idrottsvetenskap|Nationalekonomi)/i);return m?m[1]:''}
function captureVerified(){const t=document.body?.innerText||'';if(/Verifierad källa|motor v2\\.1/i.test(t)){const m=t.match(/(\\d+(?:[,.]\\d+)?)\\s*hp kan räknas in i examen\\s*[·•]\\s*(\\d+(?:[,.]\\d+)?)\\s*hp kvar/i);const s=subjectFromText(t);if(m&&s)save(s,Number(m[1].replace(',','.')),Number(m[2].replace(',','.')),'verified-v2.1')}
if(/Din studieplan/i.test(t)){const c=t.match(/(\\d+(?:[,.]\\d+)?)\\s*hp\\s*kan räknas in i examen/i),r=t.match(/(\\d+(?:[,.]\\d+)?)\\s*hp\\s*kvar att läsa/i),s=subjectFromText(t);if(r&&s)save(s,c?Number(c[1].replace(',','.')):180-Number(r[1].replace(',','.')),Number(r[1].replace(',','.')),'planner')}}
function directVerified(o){try{if(typeof window.universityOptionsForOpportunity!=='function')return null;const rows=window.universityOptionsForOpportunity(o);if(!Array.isArray(rows)||!rows.length)return null;const vals=rows.map(r=>({remaining:Number(r?.path?.remaining??r?.remaining),credited:Number(r?.path?.credited??r?.credited)})).filter(x=>Number.isFinite(x.remaining));if(!vals.length)return null;vals.sort((a,b)=>a.remaining-b.remaining);const v=vals[0],total=Number(o?.totalHp||o?.total||180);return{remaining:hp(v.remaining),credited:Number.isFinite(v.credited)?hp(v.credited):hp(total-v.remaining),source:'universityOptionsForOpportunity'}}catch(e){return null}}
function authority(o){const s=o?.subject||o?.name||o?.title||'';const d=directVerified(o);if(d){save(s,d.credited,d.remaining,d.source);return d}return get(s)}
function install(){if(typeof window.opportunityRemainingLabel==='function'&&!window.opportunityRemainingLabel.__v597){const old=window.opportunityRemainingLabel;const fn=function(o){const a=authority(o);return a?(a.remaining?fmt(a.remaining)+' hp kvar':'Klar'):old.apply(this,arguments)};fn.__v597=true;window.opportunityRemainingLabel=fn}
if(typeof window.opportunityStatus==='function'&&!window.opportunityStatus.__v597){const old=window.opportunityStatus;const fn=function(o){const a=authority(o);if(a)return a.remaining?fmt(a.remaining)+' hp kvar':'Klar';return old.apply(this,arguments)};fn.__v597=true;window.opportunityStatus=fn}}
function sync(){captureVerified();install();const all=read();for(const [k,a] of Object.entries(all)){for(const el of document.querySelectorAll('h1,h2,h3,h4,strong,b')){if(!norm(el.textContent).includes(k))continue;let box=el;for(let i=0;i<7&&box;i++,box=box.parentElement){const txt=box.innerText||'';if(txt.length>2200||!/hp\\s*kvar/i.test(txt))continue;for(const leaf of box.querySelectorAll('*')){if(leaf.children.length)continue;const x=(leaf.textContent||'').trim();if(/^\\d+(?:[,.]\\d+)?\\s*hp\\s*kvar$/i.test(x))leaf.textContent=fmt(a.remaining)+' hp kvar';else if(/^\\d+(?:[,.]\\d+)?\\s*hp kan räknas/i.test(x))leaf.textContent=fmt(a.credited)+' hp kan räknas'}break}}}
const latest=Object.values(all).sort((a,b)=>(b.ts||0)-(a.ts||0))[0];if(latest&&/Studielots analyserar|Tar fram din studieplan/i.test(document.body?.innerText||'')){for(const el of document.querySelectorAll('*')){if(el.children.length)continue;const x=(el.textContent||'').trim();if(/^\\d+(?:[,.]\\d+)?\\s*hp kvar$/i.test(x))el.textContent=fmt(latest.remaining)+' hp kvar'}}document.documentElement.dataset.studielotsPatch=VERSION}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(sync,0));else setTimeout(sync,0);let q=false;new MutationObserver(()=>{if(q)return;q=true;requestAnimationFrame(()=>{q=false;sync()})}).observe(document.documentElement,{subtree:true,childList:true,characterData:true});window.__studielotsLatestPatch={version:VERSION,patch:'2026-09-01-j',hpSource:'verified-university-path'};
})();
<\/script>`;
self.addEventListener('fetch',event=>{const u=new URL(event.request.url);if(u.pathname==='/share-ladok'&&event.request.method==='POST'){event.respondWith((async()=>{try{const form=await event.request.formData(),file=form.get('ladokPdf');if(!file)return Response.redirect('/?studielots-share-error=1',303);const c=await caches.open('studielots-share-v1');await c.put('/__studielots_shared_pdf__',new Response(file,{headers:{'content-type':file.type||'application/pdf','x-studielots-filename':file.name||'Ladok-resultatintyg.pdf'}}));return Response.redirect('/?studielots-share=1',303)}catch(e){return Response.redirect('/?studielots-share-error=1',303)}})());return}if(event.request.mode==='navigate'&&event.request.method==='GET'&&u.origin===self.location.origin){event.respondWith((async()=>{try{const response=await fetch(event.request,{cache:'no-store'}),type=response.headers.get('content-type')||'';if(!type.includes('text/html'))return response;let html=await response.text();html=html.replace(/<style id="studielots-latest-patch">[\\s\\S]*?<\\/script>/g,'').replace('</body>',latestPatch+'\\n</body>');const headers=new Headers(response.headers);headers.delete('content-length');headers.set('cache-control','no-store, max-age=0');headers.set('x-studielots-patch',STUDIELOTS_PATCH);return new Response(html,{status:response.status,statusText:response.statusText,headers})}catch(e){return fetch(event.request)}})())}});
