const STUDIELOTS_PATCH='2026-09-01-n';
self.addEventListener('install',()=>self.skipWaiting());
self.addEventListener('activate',e=>e.waitUntil(self.clients.claim()));
const latestPatch=`
<style id="studielots-latest-patch">
.lotsen-bottomnav,.v341-bottomnav,.v444-bottomnav{bottom:max(5px,env(safe-area-inset-bottom,0px))!important;width:min(680px,calc(100% - 18px))!important;padding:4px 5px!important;border-radius:27px!important;background:rgba(249,249,246,.70)!important;-webkit-backdrop-filter:blur(20px) saturate(145%)!important;backdrop-filter:blur(20px) saturate(145%)!important;border:1px solid rgba(255,255,255,.72)!important;box-shadow:0 7px 24px rgba(16,24,40,.12)!important}.lotsen-bottomnav button,.v341-bottomnav button,.v444-bottomnav button{padding:5px 2px 4px!important;min-height:48px!important;border-radius:21px!important}.lotsen-bottomnav b,.v341-bottomnav b,.v444-bottomnav b{font-size:10px!important}.main{padding-bottom:calc(78px + env(safe-area-inset-bottom,0px))!important}
#sl-pace-picker{margin:12px 0 16px;padding:14px;border-radius:18px;background:#fff;border:1px solid rgba(15,76,67,.10);box-shadow:0 4px 16px rgba(15,76,67,.05)}#sl-pace-picker .sl-pace-title{font-weight:800;font-size:15px;margin-bottom:3px;color:#113d3a}#sl-pace-picker .sl-pace-sub{font-size:12px;color:#74807f;margin-bottom:10px}#sl-pace-picker .sl-pace-options{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}#sl-pace-picker button{appearance:none;border:1px solid rgba(15,76,67,.16);background:#f6f8f7;color:#155f57;border-radius:14px;padding:10px 5px;font-weight:800;font-size:13px}#sl-pace-picker button.active{background:#155f57;color:#fff;border-color:#155f57}#sl-pace-picker .sl-pace-note{font-size:11px;color:#74807f;margin-top:9px;line-height:1.35}.sl-fast-path-note{margin:8px 0 14px;padding:10px 12px;border-radius:14px;background:#f4f8f7;color:#155f57;font-size:12px;line-height:1.4}
@media(max-width:700px){.v21-detail{overflow:hidden!important}.v21-detail-top{display:block!important}.v21-back,.v21-score{display:none!important}.v21-detail-title{width:100%!important;padding:0!important}.v21-detail-title h1{overflow-wrap:anywhere!important}#opportunityAnalysisModal .course-row,#opportunityAnalysisModal .analysis-row,.v21-detail .course-row,.v21-detail .analysis-row{display:grid!important;grid-template-columns:minmax(0,1fr) auto!important;gap:10px!important;align-items:start!important;width:100%!important}#opportunityAnalysisModal .course-row>*,#opportunityAnalysisModal .analysis-row>*,.v21-detail .course-row>*,.v21-detail .analysis-row>*{min-width:0!important;width:auto!important;max-width:none!important}#opportunityAnalysisModal .course-row>*:first-child,#opportunityAnalysisModal .analysis-row>*:first-child,.v21-detail .course-row>*:first-child,.v21-detail .analysis-row>*:first-child{overflow-wrap:normal!important;word-break:normal!important;white-space:normal!important}#opportunityAnalysisModal .course-row>*:last-child,#opportunityAnalysisModal .analysis-row>*:last-child,.v21-detail .course-row>*:last-child,.v21-detail .analysis-row>*:last-child{white-space:nowrap!important;text-align:right!important}}
#plannerClean .v572-shell.sl-terms-collapsed .v572-studyplan{display:none!important}#plannerClean .v572-term-section[data-term-section="0"],#plannerClean .v572-term[data-term="0"]{display:none!important}
</style>
<script id="studielots-latest-patch-js">
(()=>{
const VERSION='601',PACE_KEY='studielots_planner_pace_hp';
const hp=n=>Math.round((Number(n)||0)*2)/2,fmt=n=>String(hp(n)).replace('.',',');
function getPace(){const n=Number(localStorage.getItem(PACE_KEY));return[30,37.5,45].includes(n)?n:30}
function setPace(n){n=Number(n);if(![30,37.5,45].includes(n))n=30;localStorage.setItem(PACE_KEY,String(n));window.__studielotsPlannerMaxHp=n;window.__studielotsBuild={...(window.__studielotsBuild||{}),maxPlannedHpPerTerm:n,plannerPaceSelectable:true};window.dispatchEvent(new CustomEvent('studielots:pacechange',{detail:{maxHpPerTerm:n}}));['renderPlannerClean','renderPlanner','renderPlan','renderStudyPlan'].forEach(name=>{try{if(typeof window[name]==='function')window[name]()}catch(e){}});ensurePacePicker()}
function ensurePacePicker(){const root=document.querySelector('#plannerClean');if(!root)return;let box=document.querySelector('#sl-pace-picker');if(!box){box=document.createElement('div');box.id='sl-pace-picker';box.innerHTML='<div class="sl-pace-title">Studietakt</div><div class="sl-pace-sub">Välj hur mycket du maximalt vill läsa per termin</div><div class="sl-pace-options"><button data-pace="30">30 hp</button><button data-pace="37.5">37,5 hp</button><button data-pace="45">45 hp</button></div><div class="sl-pace-note">30 hp är normal heltidsfart. Högre takt används bara när det faktiskt kan korta vägen till examen.</div>';box.addEventListener('click',e=>{const b=e.target.closest('button[data-pace]');if(b)setPace(b.dataset.pace)});const shell=root.querySelector('.v572-shell')||root;root.insertBefore(box,shell)}const pace=getPace();box.querySelectorAll('button[data-pace]').forEach(b=>b.classList.toggle('active',Number(b.dataset.pace)===pace));window.__studielotsPlannerMaxHp=pace;window.__studielotsBuild={...(window.__studielotsBuild||{}),maxPlannedHpPerTerm:pace,plannerPaceSelectable:true};let note=root.querySelector('.sl-fast-path-note');if(pace>30){if(!note){note=document.createElement('div');note.className='sl-fast-path-note';box.insertAdjacentElement('afterend',note)}const extra=fmt(pace-30);note.textContent='Snabbare väg vald: StudieLots får föreslå upp till '+fmt(pace)+' hp per termin (upp till '+extra+' hp extra) när det kan tidigarelägga examen.'}else if(note)note.remove()}
function v21Authority(o){try{if(!o||typeof window.universityOptionsForOpportunity!=='function')return null;const rows=window.universityOptionsForOpportunity(o);if(!Array.isArray(rows)||!rows.length)return null;const valid=rows.map(r=>({remaining:Number(r?.v2?.remaining??r?.remaining),row:r})).filter(x=>Number.isFinite(x.remaining)).sort((a,b)=>a.remaining-b.remaining);if(!valid.length)return null;const remaining=hp(valid[0].remaining),total=Number(o?.total||o?.totalHp||(o?.source==='advanced'?(String(o?.degreeType||'').toLowerCase()==='magister'?60:120):180));return{remaining,credited:hp(total-remaining),row:valid[0].row}}catch(e){return null}}
function normalizeOpportunity(o){if(!o||typeof o!=='object')return o;const a=v21Authority(o);if(!a)return o;return{...o,remaining:a.remaining,credited:a.credited,score:Math.max(0,Math.min(100,Math.round(100*a.credited/Math.max(1,a.credited+a.remaining))))}}
function wrapSafe(){const cur=window.safeDegreeOpportunities;if(typeof cur!=='function'||cur.__sl601)return;const base=cur.__slBase||cur;const fn=function(){const rows=base.apply(this,arguments);return Array.isArray(rows)?rows.map(normalizeOpportunity):rows};fn.__sl601=true;fn.__slBase=base;window.safeDegreeOpportunities=fn}
function wrapCalc(name,maker){const cur=window[name];if(typeof cur!=='function'||cur.__sl601)return;const base=cur.__slBase||cur;const fn=maker(base);fn.__sl601=true;fn.__slBase=base;window[name]=fn}
function install(){wrapSafe();wrapCalc('canonicalRemaining',base=>function(o){const a=v21Authority(o);return a?a.remaining:base.apply(this,arguments)});wrapCalc('opportunityRemainingLabel',base=>function(o){const a=v21Authority(o);return a?(a.remaining?fmt(a.remaining)+' hp kvar':'Klar'):base.apply(this,arguments)});wrapCalc('opportunityStatus',base=>function(o){const a=v21Authority(o);return a?(a.remaining?fmt(a.remaining)+' hp kvar':'Klar'):base.apply(this,arguments)});const pace=getPace();window.__studielotsPlannerMaxHp=pace;window.__studielotsBuild={...(window.__studielotsBuild||{}),maxPlannedHpPerTerm:pace,plannerPaceSelectable:true};document.documentElement.dataset.studielotsPatch=VERSION}
function fixBreakdownLayout(){document.querySelectorAll('body *').forEach(el=>{if(el.children.length<2)return;const t=(el.innerText||'').trim();if(!(/successiv fördjupning/i.test(t)||/Resterande\s+90\s+hp/i.test(t)))return;const r=el.getBoundingClientRect();if(r.width>0&&r.width<260){el.style.width='100%';el.style.maxWidth='none';el.style.minWidth='0';el.style.display='grid';el.style.gridTemplateColumns='minmax(0,1fr) auto';el.style.columnGap='12px';Array.from(el.children).forEach((c,i)=>{c.style.minWidth='0';c.style.width='auto';c.style.maxWidth='none';if(i===el.children.length-1){c.style.whiteSpace='nowrap';c.style.textAlign='right'}})}})}
function sync(){install();ensurePacePicker();fixBreakdownLayout()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(sync,0));else setTimeout(sync,0);
let tries=0;const timer=setInterval(()=>{sync();if(++tries>60)clearInterval(timer)},250);
new MutationObserver(()=>{ensurePacePicker()}).observe(document.documentElement,{childList:true,subtree:true});
window.__studielotsLatestPatch={version:VERSION,patch:'2026-09-01-n',hpSource:'safeDegreeOpportunities-v2.1-normalized',mobileBreakdown:true,plannerPace:[30,37.5,45]};
})();
<\/script>`;
self.addEventListener('fetch',event=>{const u=new URL(event.request.url);if(u.pathname==='/share-ladok'&&event.request.method==='POST'){event.respondWith((async()=>{try{const form=await event.request.formData(),file=form.get('ladokPdf');if(!file)return Response.redirect('/?studielots-share-error=1',303);const c=await caches.open('studielots-share-v1');await c.put('/__studielots_shared_pdf__',new Response(file,{headers:{'content-type':file.type||'application/pdf','x-studielots-filename':file.name||'Ladok-resultatintyg.pdf'}}));return Response.redirect('/?studielots-share=1',303)}catch(e){return Response.redirect('/?studielots-share-error=1',303)}})());return}if(event.request.mode==='navigate'&&event.request.method==='GET'&&u.origin===self.location.origin){event.respondWith((async()=>{try{const response=await fetch(event.request,{cache:'no-store'}),type=response.headers.get('content-type')||'';if(!type.includes('text/html'))return response;let html=await response.text();html=html.replace(/<style id="studielots-latest-patch">[\\s\\S]*?<\\/script>/g,'').replace('</body>',latestPatch+'\\n</body>');const headers=new Headers(response.headers);headers.delete('content-length');headers.set('cache-control','no-store, max-age=0');headers.set('x-studielots-patch',STUDIELOTS_PATCH);return new Response(html,{status:response.status,statusText:response.statusText,headers})}catch(e){return fetch(event.request)}})())}});