(()=>{'use strict';
const pages=[...document.querySelectorAll('.page')],nav=[...document.querySelectorAll('[data-nav]')];
const state={page:'home',route:'ordinary',source:'ladok',courses:[],selectedOpportunity:null};
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
const fmt=n=>Number(n||0).toLocaleString('sv-SE',{maximumFractionDigits:1});
const escapeHtml=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const degreeSubjects=['Idrottsvetenskap','Företagsekonomi','Psykologi','Folkhälsovetenskap','Sociologi','Nationalekonomi'];
function show(id){state.page=id;pages.forEach(p=>p.classList.toggle('active',p.id===id));nav.forEach(b=>b.classList.toggle('active',b.dataset.nav===id));if(id==='opportunities')renderOpportunities();window.scrollTo({top:0,behavior:'instant'});}
function route(kind){state.route=kind;qa('[data-route]').forEach(b=>b.classList.toggle('active',b.dataset.route===kind));q('#ordinaryPlan').hidden=kind!=='ordinary';q('#fastPlan').hidden=kind!=='fast';}
function source(kind){state.source=kind;qa('[data-source]').forEach(b=>b.classList.toggle('active',b.dataset.source===kind));q('#sourceCopy').textContent=kind==='ladok'?'Ladda upp ett nationellt resultatintyg från Ladok.':'Antagning.se-import kopplas in i nästa steg.';q('#uploadBtn').disabled=kind!=='ladok';q('#uploadBtn').style.opacity=kind==='ladok'?'1':'.55';}
function toggleTerm(btn){const list=btn.closest('.term-row')?.querySelector('.course-list');if(!list)return;list.hidden=!list.hidden;const c=btn.querySelector('.chev');if(c)c.textContent=list.hidden?'⌄':'⌃';}
function evaluateSubject(subject){const engine=window.StudieLotsV2?.engine;if(!engine)return null;const r=engine.evaluate(state.courses,{totalHp:180,subject,subjectHp:90,thesisHp:15,excludeAdvancedFromTotal:true});const completed=Math.max(0,180-r.remainingHp),pct=Math.max(0,Math.min(100,Math.round(completed/180*100)));return{subject,name:`${subject}, kandidat`,completed,pct,remaining:r.remainingHp,subjectHp:r.completed.subjectHp,thesisHp:r.completed.thesisHp}}
function opportunities(){if(!state.courses.length)return[];const inferred=[...new Set(state.courses.map(c=>c.subject).filter(Boolean))];return [...new Set([...inferred,...degreeSubjects])].map(evaluateSubject).filter(Boolean).sort((a,b)=>b.pct-a.pct||a.remaining-b.remaining).slice(0,5)}
function renderOpportunities(){const host=q('#opportunities .opportunity-list');if(!host)return;if(!state.courses.length){host.innerHTML='<div class="info-note"><b>Hämta dina meriter först</b><span>Ladda upp ett Ladok-intyg så räknar vi fram dina närmaste examensvägar.</span><button class="btn-primary" data-empty-import>Hämta meriter <span>→</span></button></div>';host.querySelector('[data-empty-import]')?.addEventListener('click',()=>show('studies'));return}const rows=opportunities();host.innerHTML=rows.map((r,i)=>`<button class="opportunity compact-op" data-op="${i}"><div class="op-copy"><b>${escapeHtml(r.name)}</b><span>Preliminär examensmatchning</span></div><div class="op-score"><strong>${r.pct}%</strong><span>${fmt(r.completed)} hp klara</span></div><div class="op-progress"><i style="width:${r.pct}%"></i></div><span class="op-arrow">→</span></button>`).join('');host.querySelectorAll('[data-op]').forEach(btn=>btn.addEventListener('click',()=>openOpportunity(rows[Number(btn.dataset.op)])));}
function openOpportunity(item){state.selectedOpportunity=item;const head=q('#planner .planner-top div');if(head)head.innerHTML=`<b>${escapeHtml(item.name)}</b><span>Preliminär examensmatchning</span>`;const progress=q('#planner .planner-progress');if(progress)progress.innerHTML=`<div><strong>${fmt(item.completed)} / 180 hp</strong><span>${item.pct} %</span></div><div class="op-progress"><i style="width:${item.pct}%"></i></div><small>${fmt(item.remaining)} hp återstår preliminärt</small>`;const ordinary=q('#ordinaryPlan');if(ordinary)ordinary.innerHTML=`<div class="info-note"><b>Matchningen är klar</b><span>${fmt(item.subjectHp)} hp har preliminärt identifierats inom ${escapeHtml(item.subject)}${item.thesisHp?` · ${fmt(item.thesisHp)} hp uppsats identifierad`:''}. Nästa steg är att koppla den officiella programstrukturen så varje återstående kurs hamnar på rätt termin.</span></div><button id="fastCta" class="fast-entry"><span><b>⚡ Snabbare väg</b><small>Blir tillgänglig när ordinarie studieplan är verifierad</small></span><strong>→</strong></button>`;q('#fastCta')?.addEventListener('click',()=>route('fast'));route('ordinary');show('planner')}
function renderImported(courses){const summary=window.StudieLotsV2?.engine?.summarizeCourses(courses)||{courseCount:courses.length,totalHp:courses.reduce((s,c)=>s+Number(c.hp||0),0),institutionCount:new Set(courses.map(c=>c.institution)).size};const box=q('#uploadState');box.innerHTML=`<b>${summary.courseCount} kurser · ${fmt(summary.totalHp)} hp</b><span>${summary.institutionCount} lärosäten hittades. Meriterna är redo för matchning.</span><button class="btn-primary" id="continueMatch">Se möjligheter <span>→</span></button>`;box.style.display='grid';q('#continueMatch')?.addEventListener('click',()=>show('opportunities'));renderOpportunities();}
async function importFile(file){if(!file)return;const box=q('#uploadState');box.innerHTML=`<b>Läser ${escapeHtml(file.name)}</b><span>Hämtar kurser från intyget…</span>`;box.style.display='grid';try{if(state.source!=='ladok')throw new Error('Välj Ladok för den här importen.');const result=await window.StudieLotsV2?.ladok?.parseFile(file);if(!result)throw new Error('Ladok-läsaren kunde inte starta.');state.courses=result.courses;sessionStorage.setItem('studielots_v2_courses',JSON.stringify(state.courses));renderImported(state.courses)}catch(err){box.innerHTML=`<b>Importen kunde inte slutföras</b><span>${escapeHtml(err?.message||err)}</span>`}}
nav.forEach(b=>b.addEventListener('click',()=>show(b.dataset.nav)));
qa('[data-go]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.go)));
qa('[data-route]').forEach(b=>b.addEventListener('click',()=>route(b.dataset.route)));
qa('[data-source]').forEach(b=>b.addEventListener('click',()=>source(b.dataset.source)));
qa('.term-summary').forEach(b=>b.addEventListener('click',()=>toggleTerm(b)));
q('#fileInput')?.addEventListener('change',e=>importFile(e.target.files?.[0]));q('#uploadBtn')?.addEventListener('click',()=>q('#fileInput')?.click());q('#fastCta')?.addEventListener('click',()=>route('fast'));
try{state.courses=JSON.parse(sessionStorage.getItem('studielots_v2_courses')||'[]')}catch(e){}show('home');route('ordinary');source('ladok');renderOpportunities();
})();