(()=>{'use strict';
const pages=[...document.querySelectorAll('.page')],nav=[...document.querySelectorAll('[data-nav]')];
const state={page:'home',route:'ordinary',source:'ladok',courses:[],selectedOpportunity:null,plannerData:null};
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)],fmt=n=>Number(n||0).toLocaleString('sv-SE',{maximumFractionDigits:1});
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const degreeSubjects=['Idrottsvetenskap','Företagsekonomi','Psykologi','Folkhälsovetenskap','Sociologi','Nationalekonomi'];
function show(id){state.page=id;pages.forEach(p=>p.classList.toggle('active',p.id===id));nav.forEach(b=>b.classList.toggle('active',b.dataset.nav===id));if(id==='opportunities')renderOpportunities();if(id==='programs')window.StudieLotsV2?.programs?.load?.();window.scrollTo({top:0,behavior:'instant'})}
async function route(kind='ordinary'){if(kind==='fast'&&!state.plannerData?.verified)return;state.route=kind;qa('[data-route]').forEach(b=>b.classList.toggle('active',b.dataset.route===kind));q('#ordinaryPlan').hidden=kind!=='ordinary';q('#fastPlan').hidden=kind!=='fast';if(kind==='fast')await renderFast()}
function source(kind){state.source=kind;qa('[data-source]').forEach(b=>b.classList.toggle('active',b.dataset.source===kind));q('#sourceCopy').textContent=kind==='ladok'?'Ladda upp ett nationellt resultatintyg från Ladok.':'Antagning.se-import kopplas in i nästa steg.';q('#uploadBtn').disabled=kind!=='ladok';q('#uploadBtn').style.opacity=kind==='ladok'?'1':'.55'}
function evaluateSubject(subject){const e=window.StudieLotsV2?.engine;if(!e)return null;const r=e.evaluate(state.courses,{totalHp:180,subject,subjectHp:90,thesisHp:15,excludeAdvancedFromTotal:true}),completed=Math.max(0,180-r.remainingHp),pct=Math.round(completed/1.8);return{subject,name:`${subject}, kandidat`,completed,pct,remaining:r.remainingHp,ruleStatus:'preliminary'}}
function opportunities(){if(!state.courses.length)return[];const inferred=[...new Set(state.courses.map(c=>c.subject).filter(Boolean))];return[...new Set([...inferred,...degreeSubjects])].map(evaluateSubject).filter(Boolean).sort((a,b)=>b.pct-a.pct||a.remaining-b.remaining).slice(0,5)}
function localRule(item,university){const d=window.StudieLotsV2?.degreeRules?.evaluate?.(state.courses,{university,subject:item.subject,kind:'candidate'});if(!d)return null;const base=d.result||{},blocking=(d.checks||[]).filter(x=>x.status==='failed'),unknown=(d.checks||[]).filter(x=>x.status==='unknown'),missing=d.missingRequiredCodes||[];let remaining=Number(base.remainingHp||0);if(blocking.length||missing.length)remaining=Math.max(remaining,0.1);const completed=Math.max(0,Number(d.rule?.totalHp||180)-Number(base.remainingHp||0));return{...d,completed,remaining,blocking,unknown,missing,clear:!blocking.length&&!missing.length&&!unknown.length&&Number(base.remainingHp||0)<=0}}
function ruleMeta(local){if(!local)return'<span>Preliminär generell matchning</span>';if(local.blocking.length||local.missing.length)return'<span>Verifierad examensregel · lokala krav saknas</span>';if(local.unknown.length)return'<span>Verifierad examensregel · vissa krav behöver verifieras</span>';return'<span>Verifierad examensregel</span>'}
function renderOpportunities(){const host=q('#opportunities .opportunity-list');if(!host)return;if(!state.courses.length){host.innerHTML='<div class="info-note"><b>Hämta dina meriter först</b><span>Ladda upp ett Ladok-intyg så räknar vi fram dina närmaste examensvägar.</span><button class="btn-primary" data-import>Hämta meriter →</button></div>';host.querySelector('[data-import]')?.addEventListener('click',()=>show('studies'));return}const rows=opportunities();host.innerHTML=rows.map((r,i)=>`<button class="opportunity compact-op" data-op="${i}"><div class="op-copy"><b>${esc(r.name)}</b><span>Preliminär generell matchning · välj lärosäte för lokal kontroll</span></div><div class="op-score"><strong>${r.pct}%</strong><span>${fmt(r.completed)} hp klara</span></div><div class="op-progress"><i style="width:${r.pct}%"></i></div><span class="op-arrow">→</span></button>`).join('');host.querySelectorAll('[data-op]').forEach(b=>b.addEventListener('click',()=>chooseUniversity(rows[+b.dataset.op])))}
async function chooseUniversity(item){state.selectedOpportunity=item;const host=q('#opportunities .opportunity-list');host.innerHTML='<div class="info-note"><b>Söker lärosäten…</b><span>Kontrollerar program och lokala examensregler.</span></div>';try{const universities=await window.StudieLotsV2.paths.discover(item.subject,'candidate');if(!universities.length){host.innerHTML='<div class="info-note"><b>Ingen säker programträff hittades</b><span>Examensmatchningen finns kvar, men vi visar inte en terminsplan utan ett faktiskt programunderlag.</span><button class="btn-secondary" data-back>← Tillbaka</button></div>';host.querySelector('[data-back]')?.addEventListener('click',renderOpportunities);return}const enriched=universities.slice(0,12).map(u=>({...u,local:localRule(item,u.university)}));host.innerHTML=`<div class="page-title compact-title"><h2>Välj lärosäte</h2><p>${esc(item.name)}</p></div>`+enriched.map((u,i)=>`<button class="opportunity compact-op" data-uni="${i}"><div class="op-copy"><b>${esc(u.university)}</b><span>${esc(u.programName)}</span>${ruleMeta(u.local)}</div>${u.local?`<div class="op-score"><strong>${Math.round(100*u.local.completed/Math.max(1,u.local.rule.totalHp||180))}%</strong><span>${u.local.clear?'Examenskrav uppfyllda':u.local.unknown.length?'lokal kontroll delvis möjlig':'lokalt kontrollerad'}</span></div>`:''}<span class="op-arrow">→</span></button>`).join('');host.querySelectorAll('[data-uni]').forEach(b=>b.addEventListener('click',()=>openStructure({...item,localRule:enriched[+b.dataset.uni].local},enriched[+b.dataset.uni],b)))}catch(_){renderOpportunities()}}
async function openStructure(item,university,button){button.querySelector('.op-copy span').textContent='Hämtar officiellt studieupplägg…';const data=await window.StudieLotsV2.paths.structure(university,state.courses).catch(()=>null);if(!data){button.querySelector('.op-copy span').textContent='Detaljerat terminsupplägg saknas';return}data.degreeRule=item.localRule||localRule(item,university.university);state.plannerData=data;renderPlanner(item,data);show('planner')}
function courseHtml(r){const potential=r.creditMatch==='potential',status=r.credited?'Kan räknas in':potential?'Möjlig match · bör verifieras':'Kvar',detail=potential&&r.matchedCourse?`<small class="match-note">Liknar: ${esc(r.matchedCourse)}</small>`:'';return`<div class="course"><div class="course-main"><div><small>${esc(r.code||'')}</small><b>${esc(r.name||'Kurs')}</b>${detail}</div><strong>${fmt(r.hp)} hp</strong></div><span class="status ${r.credited?'':potential?'potential':'remain'}">${status}</span></div>`}
function termHtml(term,rows,idx,label){const hp=rows.reduce((s,r)=>s+Number(r.hp||0),0);return`<article class="term-row"><button class="term-summary"><div><b>${esc(label||`Termin ${term}`)}</b></div><strong>${fmt(hp)} hp</strong><span class="chev">${idx?'⌄':'⌃'}</span></button><div class="course-list" ${idx?'hidden':''}>${rows.map(courseHtml).join('')}</div></article>`}
function bindTerms(root){qa(`${root} .term-summary`).forEach(b=>b.addEventListener('click',()=>{const l=b.closest('.term-row').querySelector('.course-list');l.hidden=!l.hidden;b.querySelector('.chev').textContent=l.hidden?'⌄':'⌃'}))}
function degreeRuleNote(d){if(!d)return'';const issues=[...(d.blocking||[]).map(x=>x.label),...(d.missing||[]).map(x=>`Obligatorisk kurskod ${x} saknas`),...(d.unknown||[]).map(x=>`${x.label} · behöver verifieras`)];return`<div class="info-note"><b>Verifierad examensregel · ${esc(d.rule.university)}</b><span>${issues.length?esc(issues.slice(0,3).join(' · ')):'De lokala examenskrav som kan kontrolleras från meriterna är uppfyllda.'}</span></div>`}
function renderPlanner(item,data){const total=data.totalHp||180,credited=data.creditedHp,remaining=Math.max(0,total-credited),pct=Math.round(100*credited/Math.max(1,total)),possible=Number(data.potentialHp||0);q('#planner .planner-top div').innerHTML=`<b>${esc(data.item.programName||item.name)}</b><span>${esc(data.item.university)}</span>`;q('#planner .planner-progress').innerHTML=`<div><strong>${fmt(credited)} / ${fmt(total)} hp</strong><span>${pct} %</span></div><div class="op-progress"><i style="width:${pct}%"></i></div><small>${fmt(remaining)} hp återstår · ${data.verified?'Verifierad programplan':'Programstruktur från nationell källa'}${possible?` · ${fmt(possible)} hp möjlig match, ej inräknad`:''}</small>`+degreeRuleNote(data.degreeRule);const groups=new Map();data.rows.forEach(r=>{const t=Number(r.term)||1;if(!groups.has(t))groups.set(t,[]);groups.get(t).push(r)});q('#ordinaryPlan').innerHTML='<div class="term-list">'+[...groups].sort((a,b)=>a[0]-b[0]).map(([t,rows],i)=>termHtml(t,rows,i)).join('')+'</div>'+(data.verified?'<button class="fast-entry" id="fastCta"><span><b>⚡ Snabbare väg</b><small>Se om planen kan kortas med verifierbara kurstillfällen</small></span><b>→</b></button>':'<div class="fast-entry" aria-disabled="true"><span><b>⚡ Snabbare väg</b><small>Kräver verifierad ordinarie programplan</small></span></div>');bindTerms('#ordinaryPlan');const fast=q('[data-route="fast"]');if(data.verified)fast?.removeAttribute('hidden');else fast?.setAttribute('hidden','');q('#fastCta')?.addEventListener('click',()=>route('fast'));route('ordinary')}
async function renderFast(){const host=q('#fastPlan'),data=state.plannerData;if(!host||!data?.verified)return;host.innerHTML='<div class="info-note"><b>Optimerar studieplanen…</b><span>Kontrollerar verifierbara fristående kurstillfällen.</span></div>';const max=Number(localStorage.getItem('studielots_v2_fast_max')||30),summer=localStorage.getItem('studielots_v2_fast_summer')!=='0';const result=await window.StudieLotsV2.fast.build(data.rows,{maxHp:max,summer});host.innerHTML=`<div class="fast-controls"><span>Max per termin</span>${[30,37.5,45,60].map(x=>`<button data-max="${x}" class="${x===result.maxHp?'active':''}">${String(x).replace('.',',')} hp</button>`).join('')}</div><div class="term-list">${result.terms.map((t,i)=>termHtml(i+1,t.rows,i,t.label)).join('')}</div>`;host.querySelectorAll('[data-max]').forEach(b=>b.addEventListener('click',()=>{localStorage.setItem('studielots_v2_fast_max',b.dataset.max);renderFast()}));bindTerms('#fastPlan')}
function renderImported(courses){const s=window.StudieLotsV2?.engine?.summarizeCourses(courses)||{courseCount:courses.length,totalHp:courses.reduce((a,c)=>a+Number(c.hp||0),0),institutionCount:new Set(courses.map(c=>c.institution)).size},box=q('#uploadState');box.innerHTML=`<b>${s.courseCount} kurser · ${fmt(s.totalHp)} hp</b><span>${s.institutionCount} lärosäten hittades. Meriterna är redo för matchning.</span><button class="btn-primary" id="continueMatch">Se möjligheter →</button>`;box.style.display='grid';q('#continueMatch')?.addEventListener('click',()=>show('opportunities'));renderOpportunities()}
async function importFile(file){if(!file)return;const box=q('#uploadState');box.innerHTML=`<b>Läser ${esc(file.name)}</b><span>Hämtar kurser från intyget…</span>`;box.style.display='grid';try{if(state.source!=='ladok')throw Error('Välj Ladok för den här importen.');const r=await window.StudieLotsV2?.ladok?.parseFile(file);state.courses=r.courses;sessionStorage.setItem('studielots_v2_courses',JSON.stringify(state.courses));renderImported(state.courses)}catch(e){box.innerHTML=`<b>Importen kunde inte slutföras</b><span>${esc(e.message)}</span>`}}
window.addEventListener('studielots:v2-open-program',e=>{const d=e.detail||{},data=d.structure,p=d.programme;if(!data||!p)return;data.degreeRule=localRule({subject:p.subject},p.university);state.plannerData=data;state.selectedOpportunity={subject:p.subject,name:p.programName,localRule:data.degreeRule};renderPlanner(state.selectedOpportunity,data);show('planner')});
nav.forEach(b=>b.addEventListener('click',()=>show(b.dataset.nav)));qa('[data-go]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.go)));qa('[data-source]').forEach(b=>b.addEventListener('click',()=>source(b.dataset.source)));qa('[data-route]').forEach(b=>b.addEventListener('click',()=>route(b.dataset.route)));q('#fileInput')?.addEventListener('change',e=>importFile(e.target.files?.[0]));q('#uploadBtn')?.addEventListener('click',()=>q('#fileInput')?.click());try{state.courses=JSON.parse(sessionStorage.getItem('studielots_v2_courses')||'[]')}catch(_){}show('home');route('ordinary');source('ladok');renderOpportunities();
})();