(()=>{'use strict';
const fmt=n=>Number(n||0).toLocaleString('sv-SE',{maximumFractionDigits:1});
function n(s){return Number(String(s||'').replace(',','.').match(/\d+(?:\.\d+)?/)?.[0]||0)}
function degreeRemaining(){const p=document.querySelector('#planner .planner-progress');if(!p)return 0;const m=p.textContent.match(/([\d,.]+)\s*hp\s+återstår\s+enligt\s+examensmatchningen/i);return m?n(m[1]):0}
function selectedMax(){const a=document.querySelector('#fastPlan [data-max].active');return a?n(a.textContent):30}
function verifiedScheduled(){const p=document.querySelector('#fastPlan');if(!p)return 0;const m=p.textContent.match(/([\d,.]+)\s+av\s+([\d,.]+)\s+hp\s+kan\s+schemaläggas/i);return m?n(m[1]):0}
function buildBlocks(hp,max){const out=[];let left=Math.max(0,hp);while(left>.01){const take=Math.min(max,left);out.push(take);left-=take}return out}
function inject(){const fast=document.querySelector('#fastPlan');if(!fast||fast.hidden)return;const remain=degreeRemaining();if(remain<=0)return;const scheduled=verifiedScheduled(),max=selectedMax(),unplaced=Math.max(0,remain-scheduled);const existing=fast.querySelector('.v2-fast-capacity');if(existing)existing.remove();const copied=fast.querySelector('.term-list');if(copied&&scheduled<=0)copied.remove();const blocks=buildBlocks(unplaced,max);const box=document.createElement('section');box.className='v2-fast-capacity';box.innerHTML=`<div class="info-note"><b>Optimerad plan utifrån ${fmt(remain)} hp som återstår</b><span>${scheduled>0?`${fmt(scheduled)} hp har verifierbara kurstillfällen. `:''}${unplaced>0?`${fmt(unplaced)} hp saknar ännu verifierad kursplacering.`:'Alla återstående hp har verifierbara kurstillfällen.'} Vi visar därför inte den ordinarie sexterminsplanen som om allt måste läsas om.</span></div>${blocks.length?`<div class="v2-capacity-list">${blocks.map((x,i)=>`<div class="v2-capacity-row"><div><b>${i===0?'Nästa möjliga studieperiod':`Studieperiod ${i+1}`}</b><span>Kursplacering återstår</span></div><strong>${fmt(x)} hp</strong></div>`).join('')}</div><small class="v2-capacity-note">Detta är en kapacitetsplan, inte verifierade terminsdatum. Faktiska terminer sätts först när StudieLots hittar kurstillfällen på valt lärosäte eller distans.</small>`:''}`;fast.appendChild(box)}
function install(){if(!document.getElementById('v2-fast-ui-style')){const s=document.createElement('style');s.id='v2-fast-ui-style';s.textContent='.v2-fast-capacity{display:grid;gap:10px;margin:12px 0 20px}.v2-capacity-list{display:grid;gap:8px}.v2-capacity-row{display:flex;justify-content:space-between;align-items:center;gap:12px;background:#fff;border:1px solid rgba(0,63,54,.10);border-radius:16px;padding:14px}.v2-capacity-row div{display:grid;gap:3px}.v2-capacity-row b,.v2-capacity-row strong{color:#003f36}.v2-capacity-row span,.v2-capacity-note{font-size:12px;line-height:1.4;color:#68736f}.v2-capacity-note{display:block;padding:0 4px}';document.head.appendChild(s)}new MutationObserver(()=>requestAnimationFrame(inject)).observe(document.querySelector('#fastPlan')||document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['hidden','class']});document.addEventListener('click',e=>{if(e.target.closest('[data-max],[data-summer],[data-route="fast"]'))setTimeout(inject,80)},true);setTimeout(inject,300)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();