(()=>{'use strict';
const root=window.StudieLotsV2=window.StudieLotsV2||{},ctx=root.appContext;if(!ctx)throw new Error('StudieLots app context saknas');
const {state,q,fmt,esc,programmeLevel}=ctx;
const levelKind=()=>state.opportunityLevel==='Avancerad nivå'?'advanced':'candidate';
function candidateSubjects(){const all=root.programs?.catalog||root.programIndex?.all?.()||[],subjects=all.filter(p=>programmeLevel(p)===state.opportunityLevel).map(p=>p.subject).filter(Boolean);return[...new Set([...subjects,...state.courses.map(c=>c.subject).filter(Boolean)])]}
function evaluateSubject(subject){const e=root.engine;if(!e)return null;const advanced=state.opportunityLevel==='Avancerad nivå',total=advanced?120:180,subjectHp=advanced?60:90,advancedCourses=state.courses.filter(c=>/A1|A2|avancerad/i.test(`${c.level||''} ${c.code||''}`)),courses=advanced?advancedCourses:state.courses;if(advanced&&!courses.length)return null;const r=e.evaluate(courses,{totalHp:total,subject,subjectHp,thesisHp:advanced?30:15,excludeAdvancedFromTotal:!advanced}),completed=Math.max(0,total-r.remainingHp),pct=Math.round(100*completed/total);return{subject,name:advanced?`${subject}, master/magister`:subject,completed,pct,remaining:r.remainingHp,kind:levelKind(),ruleStatus:'preliminary'}}
function opportunities(){if(!state.courses.length)return[];return candidateSubjects().map(evaluateSubject).filter(Boolean).sort((a,b)=>b.pct-a.pct||a.remaining-b.remaining||a.subject.localeCompare(b.subject,'sv')).slice(0,10)}
function localRule(item,university){const d=root.degreeRules?.evaluate?.(state.courses,{university,subject:item.subject,kind:item.kind||levelKind()});if(!d)return null;const base=d.result||{},allChecks=d.extraChecks||d.checks||[],blocking=allChecks.filter(x=>x.status==='fail'||x.status==='failed'),unknown=allChecks.filter(x=>x.status==='unknown'),missing=d.missingRequiredCodes||[];let remaining=Number(base.remainingHp||0);if(blocking.length||missing.length)remaining=Math.max(remaining,0.1);const completed=Math.max(0,Number(d.rule?.totalHp||(item.kind==='advanced'?120:180))-Number(base.remainingHp||0));return{...d,completed,remaining,blocking,unknown,missing,clear:!blocking.length&&!missing.length&&!unknown.length&&Number(base.remainingHp||0)<=0}}
function ruleMeta(local){if(!local)return'<span>Preliminär generell matchning</span>';if(local.blocking.length||local.missing.length)return'<span>Officiell examensregel · krav återstår</span>';if(local.unknown.length)return'<span>Officiell examensregel · vissa krav behöver verifieras</span>';return'<span>Officiell examensregel · maskinellt kontrollerad</span>'}
function localRank(local){if(!local)return 0;const total=Number(local.rule?.totalHp||180),basePct=Math.max(0,Math.min(100,Math.round(100*local.completed/Math.max(1,total))));if(local.blocking.length||local.missing.length)return basePct-35-(local.blocking.length+local.missing.length)*3;if(local.unknown.length)return basePct-8-Math.min(12,local.unknown.length*2);return basePct+(local.clear?12:4)}
function levelTabs(){return`<div class="program-levels opportunity-levels"><button type="button" data-op-level="Grundnivå" class="${state.opportunityLevel==='Grundnivå'?'active':''}">Grundnivå</button><button type="button" data-op-level="Avancerad nivå" class="${state.opportunityLevel==='Avancerad nivå'?'active':''}">Avancerad nivå</button></div>`}
function bindLevelTabs(host){host.querySelectorAll('[data-op-level]').forEach(b=>b.addEventListener('click',()=>{state.opportunityLevel=b.dataset.opLevel;render()}))}
function render(){const host=q('#opportunities .opportunity-list');if(!host)return;if(!state.courses.length){host.innerHTML='<div class="info-note"><b>Hämta dina meriter först</b><span>Ladda upp ett Ladok-intyg så räknar vi fram dina närmaste examensvägar.</span><button class="btn-primary" data-import>Hämta meriter →</button></div>';host.querySelector('[data-import]')?.addEventListener('click',()=>root.navigation?.show?.('studies'));return}const rows=opportunities(),empty=state.opportunityLevel==='Avancerad nivå'?'<div class="info-note"><b>Ingen tydlig avancerad matchning ännu</b><span>Vi hittar inga avancerade meriter att rangordna. Du kan fortfarande söka alla master- och magisterprogram under Program.</span></div>':'';host.innerHTML=levelTabs()+`<p class="program-section-note">De ${Math.min(10,rows.length)} närmaste examensvägarna på ${state.opportunityLevel.toLowerCase()}, rangordnade efter dina meriter.</p>`+(rows.length?rows.map((r,i)=>`<button class="opportunity compact-op" data-op="${i}"><div class="op-copy"><b>${esc(r.name)}</b><span>Preliminär generell matchning · välj lärosäte och program</span></div><div class="op-score"><strong>${r.pct}%</strong><span>${fmt(r.completed)} hp klara</span></div><div class="op-progress"><i style="width:${r.pct}%"></i></div><span class="op-arrow">→</span></button>`).join(''):empty);bindLevelTabs(host);host.querySelectorAll('[data-op]').forEach(b=>b.addEventListener('click',()=>chooseUniversity(rows[+b.dataset.op])))}
async function chooseUniversity(item){state.selectedOpportunity=item;const host=q('#opportunities .opportunity-list');host.innerHTML='<div class="info-note"><b>Söker lärosäten…</b><span>Kontrollerar program och lokala examensregler.</span></div>';try{const universities=await root.paths.discover(item.subject,item.kind||levelKind());if(!universities.length){host.innerHTML='<div class="info-note"><b>Ingen säker programträff hittades</b><span>Examensmatchningen finns kvar. Sök gärna det specifika programmet i Program.</span><button class="btn-secondary" data-back>← Tillbaka</button></div>';host.querySelector('[data-back]')?.addEventListener('click',render);return}const enriched=universities.slice(0,40).map(u=>({...u,local:localRule(item,u.university)})).sort((a,b)=>localRank(b.local)-localRank(a.local)||(a.university||'').localeCompare(b.university||'','sv'));const grouped=[...new Set(enriched.map(x=>x.university).filter(Boolean))];host.innerHTML=`<div class="page-title compact-title"><h2>Välj lärosäte</h2><p>${esc(item.name)} · ${grouped.length} lärosäten</p></div>`+grouped.slice(0,12).map((name,i)=>`<button class="opportunity compact-op" data-uni-group="${i}"><div class="op-copy"><b>${esc(name)}</b><span>${enriched.filter(x=>x.university===name).length} relevanta program</span></div><span class="op-arrow">→</span></button>`).join('')+'<button class="btn-secondary" data-back>← Tillbaka</button>';host.querySelector('[data-back]')?.addEventListener('click',render);host.querySelectorAll('[data-uni-group]').forEach(b=>b.addEventListener('click',()=>chooseProgram(item,grouped[+b.dataset.uniGroup],enriched.filter(x=>x.university===grouped[+b.dataset.uniGroup]))))}catch(_){render()}}
function chooseProgram(item,university,programs){const host=q('#opportunities .opportunity-list');host.innerHTML=`<div class="page-title compact-title"><h2>Välj program</h2><p>${esc(university)} · ${esc(item.name)}</p></div>`+programs.map((u,i)=>`<button class="opportunity compact-op" data-program-choice="${i}"><div class="op-copy"><b>${esc(u.programName||'Program')}</b><span>${esc(u.subject||item.subject)}</span>${ruleMeta(u.local)}</div>${u.local?`<div class="op-score"><strong>${Math.round(100*u.local.completed/Math.max(1,u.local.rule.totalHp||180))}%</strong></div>`:''}<span class="op-arrow">→</span></button>`).join('')+'<button class="btn-secondary" data-back-uni>← Lärosäten</button>';host.querySelector('[data-back-uni]')?.addEventListener('click',()=>chooseUniversity(item));host.querySelectorAll('[data-program-choice]').forEach(b=>b.addEventListener('click',()=>openStructure({...item,localRule:programs[+b.dataset.programChoice].local},programs[+b.dataset.programChoice],b)))}
async function openStructure(item,university,button){const status=button.querySelector('.op-copy span'),old=status?.textContent;if(status)status.textContent='Hämtar officiellt studieupplägg…';const data=await root.paths.structure(university,state.courses).catch(()=>null);if(!data){if(status)status.textContent='Detaljerat terminsupplägg saknas';setTimeout(()=>{if(status)status.textContent=old},2200);return}data.degreeRule=item.localRule||localRule(item,university.university);root.planner?.enter?.(item,university,data)}
root.opportunities={render,localRule,levelKind};
})();