(()=>{'use strict';
const q=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m])),norm=s=>String(s??'').toLocaleLowerCase('sv-SE').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim();
let catalog=[],loaded=false,loading=false,source='studielots-ht26',activeLevel='Alla',limit=20,lastError='';
function levelOf(p){const raw=norm(`${p.level||''} ${p.programName||''}`);return /master|magister|avancerad|second cycle|specialistsjukskotersk|barnmorskeprogram/.test(raw)?'Avancerad nivå':'Grundnivå'}
function merits(){try{return JSON.parse(sessionStorage.getItem('studielots_v2_courses')||'[]')}catch(_){return[]}}
function matchesSearch(p,term){const h=norm(`${p.programName||''} ${p.university||''} ${p.subject||''} ${p.programCode||''}`);return norm(term).split(/\s+/).filter(Boolean).every(t=>h.includes(t))}
async function load(){if(loading)return;loading=true;lastError='';render();try{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),35000);let response;try{response=await fetch(`/api/program-index?catalogue=1&_=${Date.now()}`,{signal:controller.signal,headers:{accept:'application/json'},cache:'no-store'})}finally{clearTimeout(timer)}if(!response.ok)throw Error(`HTTP ${response.status}`);const data=await response.json();if(!Array.isArray(data.programs)||data.fallback||data.source!=='studielots-ht26')throw Error('Felaktig katalog');catalog=data.programs.filter(p=>p.structureCoverage==='complete'&&Array.isArray(p.rows)&&p.rows.length>0);source=data.source;loaded=true}catch(e){catalog=[];loaded=false;lastError='Kunde inte läsa kompletta program från databasen. Försök igen.';console.error('[StudieLots programs]',e)}finally{loading=false;render()}}
function render(){const host=q('#programResults'),input=q('#programSearch');if(!host)return;let levels=q('#programLevels');if(!levels){levels=document.createElement('div');levels.id='programLevels';host.before(levels)}levels.className='program-levels';levels.innerHTML=['Alla','Grundnivå','Avancerad nivå'].map(s=>`<button type="button" data-level="${s}" class="${s===activeLevel?'active':''}">${s}</button>`).join('');levels.querySelectorAll('button').forEach(b=>b.onclick=()=>{activeLevel=b.dataset.level;limit=20;render()});if(!q('#studielots-program-style')){const style=document.createElement('style');style.id='studielots-program-style';style.textContent='.program-levels{display:flex;gap:6px;margin-bottom:14px;overflow-x:auto}.program-levels button{border:1px solid var(--line);background:var(--mint);border-radius:12px;padding:10px;font-size:11px;font-weight:750;white-space:nowrap}.program-levels button.active{background:var(--teal);color:white}.program-result{width:100%;text-align:left}.program-more{width:100%;padding:12px;border-radius:12px;border:1px solid var(--line);background:var(--mint)}';document.head.appendChild(style)}const term=input?.value||'',rows=catalog.filter(p=>(activeLevel==='Alla'||levelOf(p)===activeLevel)&&matchesSearch(p,term)).sort((a,b)=>String(a.programName||'').localeCompare(String(b.programName||''),'sv')),shown=rows.slice(0,limit);let html=`<p class="program-section-note">${loading?'Laddar program från StudieLots databas…':lastError?esc(lastError):`${rows.length} sökbara program med komplett studiegång`}</p>`;if(lastError)html+='<button type="button" class="program-more" id="retry-programs">Försök igen</button>';else if(!rows.length&&!loading)html+='<div class="info-note">Inga program matchar sökningen. Prova ett annat namn eller välj Alla.</div>';html+=shown.map((p,i)=>`<button type="button" class="opportunity compact-op program-result" data-program="${i}"><div class="op-copy"><b>${esc(p.programName)}</b><span>${esc(p.university)} · ${esc(p.programCode)} · ${esc(p.programHp||'')} hp</span><small>Komplett studiegång</small></div><span class="op-arrow">→</span></button>`).join('');if(rows.length>shown.length)html+=`<button type="button" class="program-more" id="more-programs">Visa fler (${rows.length-shown.length})</button>`;host.innerHTML=html;host.querySelector('#retry-programs')?.addEventListener('click',load);host.querySelector('#more-programs')?.addEventListener('click',()=>{limit+=20;render()});host.querySelectorAll('[data-program]').forEach(b=>b.addEventListener('click',()=>open(shown[Number(b.dataset.program)],b)))}
async function open(p,b){if(!p)return;const sub=b.querySelector('.op-copy span'),old=sub?.textContent;b.disabled=true;if(sub)sub.textContent='Öppnar studiegång…';try{const data=await window.StudieLotsV2.paths.structure(p,merits());if(!data?.rows?.length)throw Error('Studiegång saknas');window.dispatchEvent(new CustomEvent('studielots:v2-open-program',{detail:{programme:p,structure:data}}))}catch(e){console.error('[StudieLots programme route]',e);if(sub)sub.textContent='Kunde inte öppna studiegången';setTimeout(()=>{if(sub)sub.textContent=old;b.disabled=false},2500)}}
function init(){const input=q('#programSearch');if(!input)return;input.placeholder='Sök program eller lärosäte';input.addEventListener('input',()=>{limit=20;render()});q('[data-nav="programs"]')?.addEventListener('click',()=>{if(!loaded)load()});if(q('#programs.page.active'))load()}
window.StudieLotsV2=window.StudieLotsV2||{};window.StudieLotsV2.programs={load,render,levelOf,matchesSearch,get catalog(){return catalog},get source(){return source},get level(){return activeLevel},get loading(){return loading}};document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init,{once:true}):init();
})();