(()=>{'use strict';
const norm=v=>String(v??'').trim().toLocaleLowerCase('sv-SE').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const code=v=>String(v??'').trim().toUpperCase().replace(/[^A-Z0-9ÅÄÖ]/g,'');
const hp=v=>Number(v?.hp??v?.credits??v?.ects??0)||0;
const stop=new Set('kurs course grundkurs fortsättningskurs introduktion till och i av för med samt inom om grundnivå avancerad nivå hp ects gr a b c d'.split(' '));
async function getJson(url,timeout=15000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);try{const response=await fetch(url,{signal:controller.signal,headers:{accept:'application/json'}});if(!response.ok)throw Error(`HTTP ${response.status}`);return await response.json()}finally{clearTimeout(timer)}}
function exactCredit(row,merits){const rc=code(row?.code),rn=norm(row?.name);return merits.find(c=>{const cc=code(c?.code),cn=norm(c?.name);return(rc&&cc&&rc===cc)||(rn&&cn&&rn===cn)})||null}
function words(v){return norm(v).replace(/[^a-zåäö0-9]+/g,' ').split(/\s+/).filter(x=>x.length>2&&!stop.has(x))}
function potentialCredit(row,merits){const rw=[...new Set(words(row?.name))],rh=hp(row);if(rw.length<2)return null;let best=null;for(const c of merits){const ch=hp(c);if(rh&&ch&&Math.abs(rh-ch)>.11)continue;const rs=norm(row?.subject),cs=norm(c?.subject);if(rs&&cs&&rs!==cs)continue;const cw=[...new Set(words(c?.name))];if(cw.length<2)continue;const used=new Set();let common=0;for(const x of rw){const i=cw.findIndex((y,j)=>!used.has(j)&&(x===y||(Math.min(x.length,y.length)>=6&&(x.startsWith(y)||y.startsWith(x)))));if(i>=0){used.add(i);common++}}const coverage=common/Math.max(1,Math.min(rw.length,cw.length)),jaccard=common/Math.max(1,rw.length+cw.length-common),score=coverage*.7+jaccard*.3;if(common>=2&&coverage>=.72&&score>(best?.score||0))best={course:c,score}}return best}
function creditMatch(row,merits){const exact=exactCredit(row,merits);if(exact)return{kind:'exact',course:exact,score:1};const potential=potentialCredit(row,merits);return potential?{kind:'potential',course:potential.course,score:potential.score}:null}
function subjectKey(v){const n=norm(v);if(/foretagsekonomi|business administration|marketing|marknadsforing|redovisning|finansiering|organisation|ledning/.test(n))return'foretagsekonomi';if(/nationalekonomi|economics|mikroekonomi|makroekonomi/.test(n))return'nationalekonomi';if(/statistik|statistics/.test(n))return'statistik';if(/handelsratt|juridik|business law|commercial law/.test(n))return'juridik';if(/psykologi|psychology/.test(n))return'psykologi';if(/idrottsvetenskap|sport science/.test(n))return'idrottsvetenskap';return n}
function rowSubject(row,programmeSubject=''){const own=subjectKey(row?.subject||row?.name||'');if(own&&own!==norm(row?.name||''))return own;const optionText=(row?.options||[]).map(x=>x?.name).join(' '),option=subjectKey(optionText);if(option&&option!==norm(optionText))return option;if(/huvudområde|huvudomrade/i.test(`${row?.name||''} ${optionText}`))return subjectKey(programmeSubject);return own}
function allocateProgrammeMatches(courseRows,merits,programmeSubject=''){const used=new Set(),out=courseRows.map((row,i)=>({...row,term:Number(row.__slOriginalTerm||row.term)||1,index:i,credited:false,creditMatch:'none',matchScore:0,matchedCourse:'',matchedCourseCode:'',matchedHp:0})),meritRows=(merits||[]).map((c,i)=>({c,i,hp:hp(c)})).filter(x=>x.hp>0);
for(const row of out){const rc=code(row.code),rn=norm(row.name),m=meritRows.find(x=>!used.has(x.i)&&((rc&&code(x.c?.code)===rc)||(rn&&norm(x.c?.name)===rn)));if(!m)continue;used.add(m.i);row.credited=true;row.creditMatch='exact';row.matchScore=1;row.matchedCourse=m.c?.name||'';row.matchedCourseCode=m.c?.code||'';row.matchedHp=Math.min(hp(row),m.hp)}
for(const row of out){if(row.credited)continue;const candidates=meritRows.filter(x=>!used.has(x.i)),single=potentialCredit(row,candidates.map(x=>x.c));if(!single)continue;const m=candidates.find(x=>x.c===single.course);if(!m)continue;used.add(m.i);row.creditMatch='potential';row.matchScore=single.score;row.matchedCourse=m.c?.name||'';row.matchedCourseCode=m.c?.code||'';row.matchedHp=Math.min(hp(row),m.hp)}
for(const row of out){if(row.credited||row.matchedHp>0||row.slotType==='main-field-or-elective-slot')continue;const need=hp(row);if(!(need>0))continue;const target=rowSubject(row,programmeSubject);if(!target)continue;const candidates=meritRows.filter(x=>!used.has(x.i)&&subjectKey(x.c?.subject||x.c?.subjectName||x.c?.name||'')===target).sort((a,b)=>b.hp-a.hp);let sum=0;const picked=[];for(const m of candidates){if(sum>=need-.01)break;picked.push(m);sum+=m.hp}if(sum<=0)continue;for(const m of picked)used.add(m.i);const matched=Math.min(need,sum);row.creditMatch=matched>=need-.01?'potential':'partial';row.matchScore=matched/need;row.matchedHp=matched;row.matchedCourse=picked.map(x=>x.c?.name||x.c?.code||'Kurs').join(' + ');row.matchedCourseCode=picked.map(x=>x.c?.code).filter(Boolean).join(', ')}return out}
async function discover(subject,kind='candidate'){try{const data=await getJson('/api/program-index?'+new URLSearchParams({subject}),35000),programs=Array.isArray(data?.programs)?data.programs:[];programs.meta={temporarilyUnavailable:false,source:data?.source||'studielots-ht26',catalogue:data?.catalogue||null};return programs.filter(p=>kind==='candidate'?!/master|magister|avancerad/i.test(`${p.level||''} ${p.programName||''}`):true)}catch(_){const empty=[];empty.meta={temporarilyUnavailable:true,source:'studielots-ht26'};return empty}}
async function structure(item,merits=[]){let programme=item;if(!Array.isArray(programme?.rows)||!programme.rows.length){const params=new URLSearchParams({q:item?.programCode||item?.programName||''}),data=await getJson('/api/program-index?'+params,15000);programme=(data?.programs||[]).find(p=>norm(p.university)===norm(item?.university)&&code(p.programCode)===code(item?.programCode))}if(!programme||programme.structureCoverage!=='complete'||!/^https:\/\//i.test(String(programme.sourceEvidenceUrl||''))||!Array.isArray(programme.rows)||!programme.rows.length)return null;const rows=allocateProgrammeMatches(programme.rows,merits,programme.subject||'');return{item:programme,source:'studielots-ht26',verified:true,sourceEvidenceUrl:programme.sourceEvidenceUrl,rows,totalHp:Number(programme.programHp)||rows.reduce((s,x)=>s+hp(x),0),creditedHp:rows.filter(x=>x.credited).reduce((s,x)=>s+Number(x.matchedHp||0),0),potentialHp:rows.filter(x=>x.creditMatch==='potential'||x.creditMatch==='partial').reduce((s,x)=>s+Number(x.matchedHp||0),0)}}
window.StudieLotsV2=window.StudieLotsV2||{};window.StudieLotsV2.paths=Object.freeze({discover,structure,exactCredit,potentialCredit,creditMatch,allocateProgrammeMatches});
})();