(()=>{'use strict';
const root=window.StudieLotsV2=window.StudieLotsV2||{},ctx=root.appContext;if(!ctx)throw new Error('StudieLots app context saknas');
const {state,q,qa,fmt,esc}=ctx;
function source(kind){state.source=kind;qa('[data-source]').forEach(b=>b.classList.toggle('active',b.dataset.source===kind));q('#sourceCopy').textContent=kind==='ladok'?'Ladda upp ett nationellt resultatintyg från Ladok.':'Antagning.se-import kopplas in i nästa steg.';q('#uploadBtn').disabled=kind!=='ladok';q('#uploadBtn').style.opacity=kind==='ladok'?'1':'.55'}
function terms(){const now=new Date(),y=now.getFullYear(),m=now.getMonth()+1,start=m<=6?{kind:'HT',year:y}:{kind:'VT',year:y+1},out=[];for(let i=0;i<6;i++){const autumn=start.kind==='HT'?i%2===0:i%2===1,year=start.year+Math.floor((i+(start.kind==='VT'?1:0))/2);out.push((autumn?'HT':'VT')+String(year).slice(-2))}return out}
function openImportResult(label){const modal=q('#meritResultModal'),select=q('#studyStartTerm'),summary=q('#meritResultSummary');if(!modal||!select||!summary){root.navigation?.show?.('opportunities');return}summary.textContent=`${state.courses.length} kurser · ${fmt(state.courses.reduce((s,c)=>s+Number(c.hp||0),0))} hp`;select.innerHTML=terms().map(t=>`<option value="${t}">${t}</option>`).join('');const saved=sessionStorage.getItem('studielots_v2_study_start_term');if(saved&&[...select.options].some(o=>o.value===saved))select.value=saved;modal.hidden=false;modal.querySelector('b').textContent=label||'Meriter hämtade'}
function confirmImport(){const select=q('#studyStartTerm'),term=select?.value;if(!term)return;state.studyStartTerm=term;try{sessionStorage.setItem('studielots_v2_study_start_term',term)}catch(_){}q('#meritResultModal').hidden=true;root.navigation?.show?.('opportunities')}
function setCourses(courses,label){state.courses=courses||[];try{sessionStorage.setItem('studielots_v2_courses',JSON.stringify(state.courses))}catch(_){}const box=q('#uploadState');if(box){box.style.display='block';box.innerHTML=`<b>${esc(label||'Meriter hämtade')}</b><span>${state.courses.length} kurser · ${fmt(state.courses.reduce((s,c)=>s+Number(c.hp||0),0))} hp</span>`}openImportResult(label)}
function bind(){q('#confirmStudyStart')?.addEventListener('click',confirmImport);q('#uploadBtn')?.addEventListener('click',()=>q('#fileInput')?.click());q('#fileInput')?.addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;const box=q('#uploadState');if(box){box.style.display='block';box.innerHTML='<b>Läser meriter…</b><span>Kurser, nivå och examen analyseras.</span>'}try{const d=await root.ladok.importPdf(f);setCourses(d.courses,d.sourceLabel||'Ladok-meriter')}catch(err){if(box)box.innerHTML=`<b>Kunde inte läsa intyget</b><span>${esc(err.message||'Prova ett nationellt resultatintyg från Ladok.')}</span>`}});qa('[data-source]').forEach(b=>b.addEventListener('click',()=>source(b.dataset.source)));window.addEventListener('studielots:v2-demo',e=>setCourses(e.detail.courses,'Exempeldata · 150 hp'));source('ladok')}
root.studies={source,setCourses,bind,confirmImport};
})();