(()=>{'use strict';
const root=window.StudieLotsV2=window.StudieLotsV2||{},ctx=root.appContext;if(!ctx)throw new Error('StudieLots app context saknas');
const {state,q,qa,fmt,esc}=ctx;
function source(kind){state.source=kind;qa('[data-source]').forEach(b=>b.classList.toggle('active',b.dataset.source===kind));q('#sourceCopy').textContent=kind==='ladok'?'Ladda upp ett nationellt resultatintyg från Ladok.':'Antagning.se-import kopplas in i nästa steg.';q('#uploadBtn').disabled=kind!=='ladok';q('#uploadBtn').style.opacity=kind==='ladok'?'1':'.55'}
function terms(){const now=new Date(),y=now.getFullYear(),m=now.getMonth()+1,out=[];let kind=m<=6?'HT':'VT',year=m<=6?y:y+1;for(let i=0;i<6;i++){out.push(kind+String(year).slice(-2));if(kind==='VT')kind='HT';else{kind='VT';year++}}return out}
function meritStats(){const courses=state.courses||[],hp=courses.reduce((s,c)=>s+Number(c.hp||0),0),institutions=new Set(courses.map(c=>c.institution).filter(Boolean)),subjects=new Set(courses.map(c=>c.subject).filter(Boolean)),advanced=courses.filter(c=>/^A/i.test(c.progression||'')).reduce((s,c)=>s+Number(c.hp||0),0),thesis=courses.filter(c=>/G2E|A2E|uppsats|examensarbete/i.test(`${c.progression||''} ${c.name||''}`)).reduce((s,c)=>s+Number(c.hp||0),0);return{courses:courses.length,hp,institutions:institutions.size,subjects:subjects.size,advanced,thesis}}
function ensureImportModal(){let modal=q('#meritResultModal');if(modal&&modal.parentElement!==document.body)document.body.appendChild(modal);if(modal)return modal;modal=document.createElement('div');modal.id='meritResultModal';modal.className='merit-result-modal';modal.hidden=true;modal.innerHTML='<div class="merit-result-card"><b>Meriter hämtade</b><div id="meritResultSummary" class="merit-result-summary"></div><label for="studyStartTerm">När planerar du att börja studera?</label><select id="studyStartTerm"></select><button type="button" id="confirmStudyStart" class="btn-primary">Visa mina möjligheter <span>→</span></button><small>StudieLots använder terminen för att bygga din studieväg från rätt start.</small></div>';document.body.appendChild(modal);q('#confirmStudyStart')?.addEventListener('click',confirmImport);return modal}
function openImportResult(label){const modal=ensureImportModal(),select=q('#studyStartTerm'),summary=q('#meritResultSummary'),s=meritStats();summary.innerHTML=`<div><strong>${s.courses}</strong><span>kurser</span></div><div><strong>${fmt(s.hp)}</strong><span>hp totalt</span></div><div><strong>${s.subjects}</strong><span>ämnen</span></div><div><strong>${s.institutions}</strong><span>lärosäten</span></div>${s.advanced? `<div><strong>${fmt(s.advanced)}</strong><span>hp avancerad nivå</span></div>`:''}${s.thesis? `<div><strong>${fmt(s.thesis)}</strong><span>hp uppsats/examensarbete</span></div>`:''}`;select.innerHTML=terms().map(t=>`<option value="${t}">${t}</option>`).join('');let saved=state.startTerm||'';try{saved=localStorage.getItem('studielots_v2_start_term')||saved}catch(_){}if(saved&&[...select.options].some(o=>o.value===saved))select.value=saved;modal.querySelector('b').textContent=label||'Meriter hämtade';modal.hidden=false;modal.style.display='grid';modal.style.pointerEvents='auto';modal.querySelector('.merit-result-card').style.pointerEvents='auto'}
function confirmImport(){const modal=q('#meritResultModal'),select=q('#studyStartTerm'),term=select?.value;if(!term)return;state.startTerm=term;try{localStorage.setItem('studielots_v2_start_term',term)}catch(_){}if(modal){modal.hidden=true;modal.style.display='none'}root.navigation?.show?.('opportunities')}
function setCourses(courses,label){state.courses=courses||[];try{sessionStorage.setItem('studielots_v2_courses',JSON.stringify(state.courses))}catch(_){}const box=q('#uploadState');if(box){box.style.display='block';box.innerHTML=`<b>${esc(label||'Meriter hämtade')}</b><span>${state.courses.length} kurser · ${fmt(state.courses.reduce((s,c)=>s+Number(c.hp||0),0))} hp</span>`}openImportResult(label)}
function bind(){const modal=ensureImportModal();modal.addEventListener('click',e=>{const btn=e.target.closest('#confirmStudyStart');if(btn){e.preventDefault();e.stopPropagation();confirmImport()}});q('#uploadBtn')?.addEventListener('click',()=>q('#fileInput')?.click());q('#fileInput')?.addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;const box=q('#uploadState');if(box){box.style.display='block';box.innerHTML='<b>Läser meriter…</b><span>Kurser, nivå och examen analyseras.</span>'}try{const d=await root.ladok.importPdf(f);setCourses(d.courses,d.sourceLabel||'Ladok-meriter')}catch(err){if(box)box.innerHTML=`<b>Kunde inte läsa intyget</b><span>${esc(err.message||'Prova ett nationellt resultatintyg från Ladok.')}</span>`}});qa('[data-source]').forEach(b=>b.addEventListener('click',()=>source(b.dataset.source)));window.addEventListener('studielots:v2-demo',e=>setCourses(e.detail.courses,'Exempeldata · 150 hp'));source('ladok')}
root.studies={source,setCourses,bind,confirmImport};
})();