(()=>{'use strict';
const VERSION='2.0';
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:0};
const text=v=>String(v??'').replace(/\s+/g,' ').trim();
const low=v=>text(v).toLocaleLowerCase('sv-SE').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const tokens=v=>new Set(low(v).split(/[^a-z0-9]+/).filter(w=>w.length>2));
const similarity=(a,b)=>{const A=tokens(a),B=tokens(b);if(!A.size||!B.size)return null;let hit=0;for(const x of A)if(B.has(x))hit++;return hit/Math.max(1,Math.min(A.size,B.size))};
const hp=c=>num(c?.hp??c?.credits??c?.ects??c?.points);
const progression=c=>text(c?.progression??c?.levelCode??c?.progressionCode??c?.level).toUpperCase().replace(/\s+/g,'');
const levelFamily=c=>{const p=progression(c);if(/^A/.test(p))return'advanced';if(/^G/.test(p))return'basic';const l=low(c?.educationLevel??c?.level);if(l.includes('avancerad')||l.includes('advanced'))return'advanced';if(l.includes('grund')||l.includes('basic')||l.includes('first cycle'))return'basic';return'unknown'};
const field=c=>text(c?.subject??c?.mainField??c?.huvudomrade??c?.field??c?.subjectArea);
const body=c=>[c?.name,c?.title,c?.description,c?.content,c?.syllabusContent,c?.learningOutcomes,c?.objectives,c?.aims].filter(Boolean).join(' ');
const historical=(source,target,history=[])=>{const sc=text(source?.code??source?.courseCode).toUpperCase(),tc=text(target?.code??target?.courseCode).toUpperCase();const rows=(Array.isArray(history)?history:[]).filter(r=>{const a=text(r?.sourceCode??r?.fromCode).toUpperCase(),b=text(r?.targetCode??r?.toCode).toUpperCase();return sc&&tc&&a===sc&&b===tc});let approved=0,partial=0,rejected=0;for(const r of rows){const s=low(r?.decision??r?.status??r?.result);if(/bifall|approved|granted/.test(s))approved++;else if(/delvis|partial/.test(s))partial++;else if(/avslag|rejected|denied/.test(s))rejected++}return{count:rows.length,approved,partial,rejected}};
function assess(source,target,opts={}){const sourceHp=hp(source),targetHp=hp(target),hpRatio=targetHp>0?sourceHp/targetHp:null;const sourceLevel=levelFamily(source),targetLevel=levelFamily(target);const levelCompatible=sourceLevel==='unknown'||targetLevel==='unknown'||sourceLevel===targetLevel||(sourceLevel==='advanced'&&targetLevel==='basic');const fieldSimilarity=similarity(field(source)||source?.name,field(target)||target?.name);const contentSimilarity=similarity(body(source),body(target));const learningSimilarity=similarity(source?.learningOutcomes??source?.objectives,target?.learningOutcomes??target?.objectives);const hist=historical(source,target,opts.history);const reasons=[],differences=[];if(hpRatio!==null&&hpRatio>=1)reasons.push('Tidigare kurs har minst samma omfattning');else if(hpRatio!==null)differences.push('Tidigare kurs har lägre omfattning');if(levelCompatible)reasons.push('Utbildningsnivån är förenlig');else differences.push('Utbildningsnivån skiljer sig');if(fieldSimilarity!==null&&fieldSimilarity>=.55)reasons.push('Huvudområde/ämne överlappar tydligt');else if(fieldSimilarity!==null&&fieldSimilarity<.3)differences.push('Huvudområde/ämne har begränsad överlappning');if(contentSimilarity!==null&&contentSimilarity>=.55)reasons.push('Kursinnehållet överlappar tydligt');else if(contentSimilarity!==null&&contentSimilarity<.3)differences.push('Kursinnehållet har begränsad överlappning');if(learningSimilarity!==null&&learningSimilarity>=.55)reasons.push('Lärandemålen överlappar tydligt');else if(learningSimilarity!==null&&learningSimilarity<.3)differences.push('Lärandemålen har begränsad överlappning');if(hist.approved>0)reasons.push(`Historiskt stöd finns (${hist.approved} bifall)`);if(hist.rejected>0)differences.push(`Historiska avslag finns (${hist.rejected})`);const evidence=[fieldSimilarity,contentSimilarity,learningSimilarity].filter(v=>v!==null);const academicStrong=evidence.length>=2&&evidence.filter(v=>v>=.55).length>=2;const hardConflict=!levelCompatible||(hpRatio!==null&&hpRatio<.75)||(evidence.length>=2&&evidence.filter(v=>v<.3).length>=2);let classification='limited';if(!hardConflict&&academicStrong&&hpRatio!==null&&hpRatio>=.9)classification='strong';else if(!hardConflict&&((evidence.some(v=>v>=.4))||hist.approved>0))classification='relevant';return Object.freeze({version:VERSION,classification,countsInStudyPlan:classification==='strong',label:classification==='strong'?'Starkt underlag':classification==='relevant'?'Relevant underlag':'Begränsat underlag',source,target,evidence:{sourceHp,targetHp,hpRatio,sourceLevel,targetLevel,levelCompatible,fieldSimilarity,contentSimilarity,learningSimilarity,historical:hist},reasons,differences,disclaimer:'StudieLots bedömning är preliminär och vägledande. Det aktuella lärosätet fattar alltid det slutliga beslutet om tillgodoräknande.'})}
window.StudieLotsEngines=window.StudieLotsEngines||{};window.StudieLotsEngines.creditTransferV2=Object.freeze({version:VERSION,assess});
})();