(()=>{'use strict';
const root=window.StudieLotsV2,host=document.querySelector('#fastPlan');if(!root||!host||root.__visibleFastPlan)return;root.__visibleFastPlan=true;
const fmt=n=>Number(n).toLocaleString('sv-SE',{maximumFractionDigits:2});
const hp=r=>Math.max(0,Number(r?.hp)||0);
const left=r=>Math.max(0,hp(r)-Math.min(hp(r),Math.max(0,Number(r?.creditedHp??(r?.credited?hp(r):0))||0,r?.creditTransferCountsInStudyPlan&&r?.creditTransfer?.classification==='strong'?Math.max(0,Number(r?.creditTransferMatchedHp)||0):0)));
let busy=false;
function show(){if(busy||host.hidden)return;const data=root.appContext?.state?.plannerData;if(!Array.isArray(data?.rows))return;const rows=data.rows.filter(r=>left(r)>.01),existing=host.querySelector('.term-list'),note=host.querySelector('.fast-visible-fallback');if(existing?.querySelector('.course')||note)return;
 // Do not pretend that unscheduled courses are a verified accelerated timetable.
 busy=true;const section=document.createElement('section');section.className='fast-visible-fallback';const message=document.createElement('div');message.className='info-note';const title=document.createElement('b');title.textContent=rows.length?'Kurser kvar att planera':'Inga kurser återstår';const description=document.createElement('span');description.textContent=rows.length?'Vi kunde inte verifiera kurstillfällen för en komprimerad terminsplan ännu. Här är kurserna som återstår att läsa; de är inte schemalagda.':'Alla kurser är preliminärt täckta. Lärosätet beslutar om tillgodoräknande.';message.append(title,description);section.append(message);
 if(rows.length){const list=document.createElement('div');list.className='term-list';const term=document.createElement('article');term.className='term-row';const header=document.createElement('button');header.type='button';header.className='term-summary';const label=document.createElement('b');label.textContent='Återstående kurser';const total=document.createElement('strong');total.textContent=fmt(rows.reduce((s,r)=>s+left(r),0))+' hp';const arrow=document.createElement('span');arrow.className='chev';arrow.textContent='⌃';header.append(label,total,arrow);const courses=document.createElement('div');courses.className='course-list';rows.forEach(r=>{const card=document.createElement('div');card.className='course';const main=document.createElement('div');main.className='course-main';const info=document.createElement('div');const code=document.createElement('small');code.textContent=r.code||'';const name=document.createElement('b');name.textContent=r.name||'Kurs';info.append(code,name);const amount=document.createElement('strong');amount.textContent=fmt(left(r))+' hp';main.append(info,amount);card.append(main);courses.append(card)});header.addEventListener('click',()=>{courses.hidden=!courses.hidden;arrow.textContent=courses.hidden?'⌄':'⌃'});term.append(header,courses);list.append(term);section.append(list)}host.append(section);busy=false;
}
const observer=new MutationObserver(()=>{if(!busy)show()});observer.observe(host,{childList:true,subtree:false,attributes:true,attributeFilter:['hidden']});show();
})();