(()=>{'use strict';
const root=window.StudieLotsV2=window.StudieLotsV2||{};
const ctx=root.appContext;
if(!ctx)throw new Error('StudieLots app context saknas');
const {q,qa,fmt,esc}=ctx;
function courseHtml(r){const potential=r.creditMatch==='potential',status=r.credited?'Kan räknas in':potential?'Möjlig match · bör verifieras':'Kvar',detail=potential&&r.matchedCourse?`<small class="match-note">Liknar: ${esc(r.matchedCourse)}</small>`:'',choices=Array.isArray(r.choiceOptions)&&r.choiceOptions.length?`<small class="match-note"><b>Valbara alternativ:</b> ${r.choiceOptions.map(esc).join(' · ')}</small>`:r.selectionMode==='recommend-current-offerings'?'<small class="match-note">StudieLots väljer ett aktuellt verifierbart kursförslag när kursutbud finns.</small>':'',offer=r.__offer||null,offerDate=offer?.startDate||offer?.start||offer?.from,offerText=offerDate?new Date(offerDate).toLocaleDateString('sv-SE',{year:'numeric',month:'short',day:'numeric'}):'',offerLink=offer?.url?`<a class="offer-link" href="${esc(offer.url)}" target="_blank" rel="noopener">${offerText?`Start ${esc(offerText)} · `:''}Se kurstillfälle ↗</a>`:'';return`<div class="course"><div class="course-main"><div><small>${esc(r.code||'')}</small><b>${esc(r.name||'Kurs')}</b>${detail}${choices}${offerLink}</div><strong>${fmt(r.hp)} hp</strong></div><span class="status ${r.credited?'':potential?'potential':'remain'}">${status}</span></div>`}
function termHtml(term,rows,idx,label){const hp=rows.reduce((s,r)=>s+Number(r.hp||0),0);return`<article class="term-row"><button class="term-summary"><div><b>${esc(label||`Termin ${term}`)}</b></div><strong>${fmt(hp)} hp</strong><span class="chev">${idx?'⌄':'⌃'}</span></button><div class="course-list" ${idx?'hidden':''}>${rows.map(courseHtml).join('')}</div></article>`}
function bindTerms(selector){qa(`${selector} .term-summary`).forEach(b=>b.addEventListener('click',()=>{const l=b.closest('.term-row').querySelector('.course-list');l.hidden=!l.hidden;b.querySelector('.chev').textContent=l.hidden?'⌄':'⌃'}))}
function degreeRuleNote(d){if(!d)return'';const issues=[...(d.blocking||[]).map(x=>x.label),...(d.missing||[]).map(x=>`Obligatorisk kurskod ${x} saknas`),...(d.unknown||[]).map(x=>`${x.label} · behöver verifieras`)];return`<div class="info-note"><b>Officiell examensregel · ${esc(d.rule.university)}</b><span>${issues.length?esc(issues.slice(0,3).join(' · ')):'De lokala examenskrav som kan kontrolleras från meriterna är uppfyllda.'}</span></div>`}
root.plannerView=Object.freeze({courseHtml,termHtml,bindTerms,degreeRuleNote});
})();
