const SUSA_SCHEMA_URL='https://api.skolverket.se/susa-navet/susa-navet-emil3.yaml';
const SUSA_FALLBACK_BASE='https://api.skolverket.se/susa-navet/emil3/';
const DISTANCE_RE=/(distans|distance|remote|online|webb)/i;
const PHYSICAL_RE=/(obligatorisk[^.\n]{0,60}(närvaro|träff)|träff(ar)?|på plats|campus)/i;
const NO_PHYSICAL_RE=/(inga? (obligatoriska )?(träffar|närvaromoment)|utan (fysiska )?träffar|helt på distans|100 ?% distans)/i;
const UH_SUBJECT_CODES={'företagsekonomi':'616','psykologi':'420','idrottsvetenskap':'434','nationalekonomi':'571','statsvetenskap':'482'};
const clean=v=>String(v??'').trim();
const norm=v=>clean(v).toLocaleLowerCase('sv-SE').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const codeNorm=v=>clean(v).toUpperCase().replace(/[^A-Z0-9ÅÄÖ]/g,'');
function pickList(data,keys){if(Array.isArray(data))return data;for(const key of keys)if(Array.isArray(data?.[key]))return data[key];return []}
function eventList(data){return pickList(data,['educationEvents','events','items','content','results','data'])}
function providerList(data){return pickList(data,['educationProviders','providers','items','content','results','data'])}
function localized(value){const xs=value?.strings||value?.urls||[];const swe=xs.find(x=>String(x?.lang||'').toLowerCase()==='swe');return clean((swe||xs[0])?.value)}
function localizedAll(value){return (value?.strings||[]).map(x=>clean(x?.value)).filter(Boolean)}
function scalarEntries(value,path='',out=[]){if(value==null)return out;if(Array.isArray(value))value.forEach((item,index)=>scalarEntries(item,`${path}[${index}]`,out));else if(typeof value==='object')Object.entries(value).forEach(([key,item])=>scalarEntries(item,path?`${path}.${key}`:key,out));else if(['string','number','boolean'].includes(typeof value))out.push({path,value});return out}
function explicitDistance(entries){return entries.some(x=>/(^|\.)distance(\.|$)/i.test(x.path)||DISTANCE_RE.test(String(x.value))&&/(study.?form|teaching.?form|delivery|attendance)/i.test(x.path))}
function firstValue(entries,re){return entries.find(x=>re.test(x.path))?.value}
function textValue(entries,re){return clean(firstValue(entries,re))}
function numberValue(entries,re){const m=String(firstValue(entries,re)??'').replace(',','.').match(/\d+(?:\.\d+)?/);return m?Number(m[0]):0}
function normalizeEvent(raw,subject){if(!raw||typeof raw!=='object')return null;const e=scalarEntries(raw);if(!explicitDistance(e))return null;const hay=e.map(x=>String(x.value)).join(' ');if(subject&&!norm(hay).includes(norm(subject)))return null;const name=textValue(e,/(^|\.)(educationName|courseName|title)(\.strings\[\d+\]\.value|\.|$)/i)||textValue(e,/^(name)$/i),university=textValue(e,/(provider|organizer|university|institution).*(name|title).*value$/i),credits=numberValue(e,/(credits?|creditPoints?|higherEducationCredits?)(\.|$)/i)||numberValue(e,/extent\.length$/i);if(!name||!university||!(credits>0))return null;return{name,code:textValue(e,/(^|\.)(courseCode|applicationCode|code)(\.|$)/i),university,subject,hp:credits,pace:numberValue(e,/(studyPace|pace|percentage)(\.|$)/i)||null,startDate:textValue(e,/(^|\.)(startDate|startsAt)(\.|$)/i),url:textValue(e,/(^|\.)(url|webpage|informationUrl|applicationUrl).*value?$/i),distance:true,currentOffering:true,verified:true}}
function normalizeResponse(data,subject){const seen=new Set();return eventList(data).map(x=>normalizeEvent(x,subject)).filter(x=>{if(!x)return false;const k=[x.code,x.name,x.university,x.startDate].join('|').toLocaleLowerCase('sv');if(seen.has(k))return false;seen.add(k);return true}).slice(0,60)}
async function schemaBase(){try{const r=await fetch(SUSA_SCHEMA_URL,{headers:{accept:'text/yaml,text/plain'},signal:AbortSignal.timeout(5000)});if(!r.ok)return SUSA_FALLBACK_BASE;const yaml=await r.text(),server=yaml.match(/^\s*-\s*url:\s*["']?([^\s"']+)/m)?.[1];if(!server)return SUSA_FALLBACK_BASE;const base=new URL(server,SUSA_SCHEMA_URL);if(!base.pathname.endsWith('/'))base.pathname+='/';return base.href}catch(_){return SUSA_FALLBACK_BASE}}
async function getJson(url,timeout=12000){const r=await fetch(url,{headers:{accept:'application/json'},signal:AbortSignal.timeout(timeout)});if(!r.ok)throw new Error(`Susa-navet ${r.status}`);return r.json()}
function totalPages(data){const n=Number(data?.totalPages??data?.page?.totalPages??data?.pagination?.totalPages);return Number.isFinite(n)&&n>0?Math.ceil(n):1}
function isActive(r){if(!r||String(r.status||'ACTIVE').toUpperCase()!=='ACTIVE')return false;const exp=r?.content?.expires;return !exp||!Number.isFinite(Date.parse(exp))||Date.parse(exp)>=Date.now()-86400000}
async function mapLimit(items,limit,worker){const out=new Array(items.length);let next=0;async function run(){for(;;){const i=next++;if(i>=items.length)return;try{out[i]=await worker(items[i],i)}catch(_){out[i]=null}}}await Promise.all(Array.from({length:Math.min(limit,items.length)},run));return out}
async function fetchAllEvents(base){const size=2000,make=p=>{const u=new URL('educationEvents',base);u.searchParams.set('schoolType','HS');u.searchParams.set('page',String(p));u.searchParams.set('size',String(size));return u};const first=await getJson(make(0)),pages=Math.min(totalPages(first),80);if(pages<=1)return eventList(first);const rest=await mapLimit(Array.from({length:pages-1},(_,i)=>i+1),5,p=>getJson(make(p)));return[first,...rest.filter(Boolean)].flatMap(eventList)}
async function fetchProviders(base){const size=2000,make=p=>{const u=new URL('educationProviders',base);u.searchParams.set('schoolType','HS');u.searchParams.set('page',String(p));u.searchParams.set('size',String(size));return u};const first=await getJson(make(0)),pages=Math.min(totalPages(first),20),parts=pages<=1?[]:await mapLimit(Array.from({length:pages-1},(_,i)=>i+1),5,p=>getJson(make(p))),map=new Map();for(const p of[first,...parts.filter(Boolean)].flatMap(providerList)){const id=clean(p?.id||p?.content?.identifier);if(id)map.set(id,p)}return map}
function sameUniversity(a,b){const x=norm(a),y=norm(b);return !!x&&!!y&&(x===y||x.includes(y)||y.includes(x))}
function subjectTerms(subject){const k=norm(subject),aliases={'företagsekonomi':['företagsekonomi','business administration'],'psykologi':['psykologi','psychology'],'idrottsvetenskap':['idrottsvetenskap','sport science'],'nationalekonomi':['nationalekonomi','economics'],'statsvetenskap':['statsvetenskap','political science']};return aliases[k]||[k]}
function matchesSubject(info,subject){if(!subject)return true;const k=norm(subject),official=UH_SUBJECT_CODES[k],subjects=info?.content?.subjects||[];if(official&&subjects.some(s=>s?.type==='UH_Subject'&&String(s?.code||'')===official))return true;const titles=localizedAll(info?.content?.title).map(norm);return subjectTerms(subject).some(term=>term&&titles.some(t=>t.includes(norm(term))))}
function hpFromInfo(info){const c=Number(info?.content?.credits?.credits);if(Number.isFinite(c)&&c>0)return c;const e=info?.content?.extent||{},n=Number(e.length)||0,u=norm(e?.unit?.code);if(!n)return 0;if(/hp|credit|ects|poang|point/.test(u))return n;if(/semester/.test(u))return n*30;if(/week|veck/.test(u))return n*1.5;return 0}
function levelText(info){return scalarEntries(info).filter(x=>/(level|progression|cycle|nivå|niva)/i.test(x.path)).map(x=>String(x.value)).join(' ')}
function matchesKind(info,kind){const k=String(kind||'candidate').toLowerCase(),text=localized(info?.content?.title)+' '+levelText(info);if(k==='candidate')return !/(master|magister|avancerad nivå|advanced level|second cycle|\bA1[NFE]\b|\bA2E\b)/i.test(text);if(['master','magister','advanced'].includes(k))return /(master|magister|avancerad nivå|advanced level|second cycle|\bA1[NFE]\b|\bA2E\b)/i.test(text);return true}
function distanceMeetingState(event){const d=localized(event?.content?.distance?.description);if(!d)return null;if(PHYSICAL_RE.test(d))return false;if(NO_PHYSICAL_RE.test(d))return true;return null}
function eventSemester(event){const start=Date.parse(event?.content?.startDate||event?.content?.start||event?.content?.from);if(Number.isFinite(start)){const d=new Date(start),m=d.getUTCMonth()+1;return d.getUTCFullYear()*10+(m<=6?1:2)}const vals=[event?.id,event?.content?.identifier,event?.content?.education].map(String);for(const v of vals){const m=[...v.matchAll(/(?:^|\.)(20\d{2})([12])(?:$|\.)/g)].at(-1);if(m)return Number(m[1])*10+Number(m[2])}return null}
function currentSemester(){const d=new Date(),m=d.getUTCMonth()+1;return d.getUTCFullYear()*10+(m<=6?1:2)}
function toCourse(event,info,provider,subject,kind,university,includeLocal){if(!isActive(event)||!isActive(info)||!isActive(provider))return null;const ec=event.content||{},ic=info.content||{},providerName=localized(provider?.content?.name),distance=Boolean(ec.distance),local=sameUniversity(providerName,university);if(!distance&&!(includeLocal&&local))return null;const cfg=norm(ic?.configuration?.code);if(!['kurs','course'].includes(cfg)||!matchesSubject(info,subject)||!matchesKind(info,kind))return null;const credits=hpFromInfo(info),name=localized(ic.title),courseCode=clean(ic.code),startDate=clean(ec.startDate||ec.start||ec.from),start=Date.parse(startDate),url=localized(ec?.application?.url)||localized(ic.url);if(!name||!providerName||!courseCode||!(credits>0)||!Number.isFinite(start)||start<Date.now()-86400000||!url)return null;const sem=eventSemester(event),offeringId=clean(event?.id||ec.identifier),educationId=clean(ec.education),openAt=clean(ec?.application?.startDate||ec?.application?.opens),closeAt=clean(ec?.application?.endDate||ec?.application?.lastApplicationDate),now=Date.now(),open=Date.parse(openAt),close=Date.parse(closeAt);return{source:'skolverket-susa-navet',sourceId:educationId,offeringId,definitionKey:[norm(providerName),codeNorm(courseCode),'course'].join('|'),offeringKey:['susa',offeringId||educationId,startDate].join('|'),name,code:courseCode,university:providerName,subject,hp:credits,pace:Number(ec?.paceOfStudy?.percentage)||null,semester:sem,term:sem?`${sem%10===1?'VT':'HT'} ${Math.floor(sem/10)}`:'',startDate,applicationOpensAt:openAt,applicationClosesAt:closeAt,applicationOpen:Number.isFinite(open)&&Number.isFinite(close)&&now>=open&&now<=close,distance,currentOffering:true,verified:true,noPhysicalMeetings:distance?distanceMeetingState(event):null,url,sameUniversity:local}}
async function fetchSusaCourses(subject,kind,university='',includeLocal=false){const base=await schemaBase(),[events,providers]=await Promise.all([fetchAllEvents(base),fetchProviders(base)]),candidates=[];for(const event of events){if(!isActive(event))continue;const sem=eventSemester(event);if(sem&&sem<currentSemester())continue;const ec=event?.content||{},provider=providers.get(clean(ec.providers?.[0]));if(!provider)continue;const distance=Boolean(ec.distance),local=sameUniversity(localized(provider?.content?.name),university);if(!distance&&!(includeLocal&&local))continue;const educationId=clean(ec.education);if(educationId)candidates.push({event,provider,educationId})}const infoCache=new Map(),joined=await mapLimit(candidates,16,async row=>{if(!infoCache.has(row.educationId))infoCache.set(row.educationId,getJson(new URL(`educationInfos/${encodeURIComponent(row.educationId)}`,base),9000).catch(()=>null));const info=await infoCache.get(row.educationId);return info?toCourse(row.event,info,row.provider,subject,kind,university,includeLocal):null}),seen=new Set(),out=[];for(const c of joined.filter(Boolean)){if(seen.has(c.offeringKey))continue;seen.add(c.offeringKey);out.push(c)}return out.sort((a,b)=>Number(b.sameUniversity)-Number(a.sameUniversity)||String(a.startDate).localeCompare(String(b.startDate))||String(a.name).localeCompare(String(b.name),'sv')).slice(0,120)}
export {eventList,explicitDistance,normalizeEvent,normalizeResponse};
export default async function handler(req,res){res.setHeader('Cache-Control','s-maxage=3600, stale-while-revalidate=86400');const subject=clean(req.query?.subject),kind=clean(req.query?.kind)||'candidate',university=clean(req.query?.university),includeLocal=String(req.query?.includeLocal||'')==='1';try{let courses;if(process.env.DISTANCE_COURSE_FEED_URL&&!includeLocal){const u=new URL(process.env.DISTANCE_COURSE_FEED_URL);if(subject)u.searchParams.set('subject',subject);u.searchParams.set('kind',kind);courses=normalizeResponse(await getJson(u,10000),subject)}else courses=await fetchSusaCourses(subject,kind,university,includeLocal);return res.status(200).json({courses,identityPolicy:{definition:'university + code + type',offering:'Susa event id + exact start date',merge:'discovery only; never replace degree/program rules'},updated:new Date().toISOString(),source:process.env.DISTANCE_COURSE_FEED_URL&&!includeLocal?'configured-feed':'skolverket-susa-navet'})}catch(error){console.error('distance-courses',error);return res.status(200).json({courses:[],updated:new Date().toISOString(),source:'skolverket-susa-navet',temporarilyUnavailable:true})}}
