const SUSA_SCHEMA_URL='https://api.skolverket.se/susa-navet/susa-navet-emil3.yaml';
const SUSA_FALLBACK_BASE='https://api.skolverket.se/susa-navet/emil3/';
const DISTANCE_RE=/(distans|distance|remote|online|webb)/i;
const PHYSICAL_RE=/(obligatorisk[^.\n]{0,60}(närvaro|träff)|träff(ar)?|på plats|campus)/i;
const NO_PHYSICAL_RE=/(inga? (obligatoriska )?(träffar|närvaromoment)|utan (fysiska )?träffar|helt på distans|100 ?% distans)/i;
const UH_SUBJECT_CODES={
  'företagsekonomi':'616',
  'psykologi':'420',
  'idrottsvetenskap':'434',
  'nationalekonomi':'571',
  'statsvetenskap':'482'
};
function scalarEntries(value,path='',out=[]){if(value==null)return out;if(Array.isArray(value))value.forEach((item,index)=>scalarEntries(item,`${path}[${index}]`,out));else if(typeof value==='object')Object.entries(value).forEach(([key,item])=>scalarEntries(item,path?`${path}.${key}`:key,out));else if(['string','number','boolean'].includes(typeof value))out.push({path,value});return out}
function firstValue(entries,keyRe){return entries.find(x=>keyRe.test(x.path))?.value}
function textValue(entries,keyRe){const value=firstValue(entries,keyRe);return value==null?'':String(value).trim()}
function numberValue(entries,keyRe){const match=String(firstValue(entries,keyRe)??'').replace(',','.').match(/\d+(?:\.\d+)?/);return match?Number(match[0]):0}
function eventList(data){if(Array.isArray(data))return data;for(const key of ['educationEvents','events','items','content','results','data'])if(Array.isArray(data?.[key]))return data[key];return []}
function providerList(data){if(Array.isArray(data))return data;for(const key of ['educationProviders','providers','items','content','results','data'])if(Array.isArray(data?.[key]))return data[key];return []}
function localized(value){const strings=value?.strings||value?.urls||[];const swe=strings.find(x=>String(x?.lang||'').toLowerCase()==='swe');return String((swe||strings[0])?.value||'').trim()}
function localizedAll(value){return (value?.strings||[]).map(x=>String(x?.value||'').trim()).filter(Boolean)}
function explicitDistance(entries){return entries.some(x=>/(^|\.)distance(\.|$)/i.test(x.path)||DISTANCE_RE.test(String(x.value))&&/(study.?form|teaching.?form|delivery|attendance)/i.test(x.path))}
function normalizeEvent(raw,subject){if(!raw||typeof raw!=='object')return null;const entries=scalarEntries(raw);if(!explicitDistance(entries))return null;const haystack=entries.map(x=>String(x.value)).join(' ');if(subject&&!haystack.toLocaleLowerCase('sv').includes(subject.toLocaleLowerCase('sv')))return null;const name=textValue(entries,/(^|\.)(educationName|courseName|title)(\.strings\[\d+\]\.value|\.|$)/i)||textValue(entries,/^(name)$/i);const university=textValue(entries,/(provider|organizer|university|institution).*(name|title).*value$/i);const hp=numberValue(entries,/(credits?|creditPoints?|higherEducationCredits?)(\.|$)/i)||numberValue(entries,/extent\.length$/i);if(!name||!university||!(hp>0))return null;return {name,code:textValue(entries,/(^|\.)(courseCode|applicationCode|code)(\.|$)/i),university,subject,hp,pace:numberValue(entries,/(studyPace|pace|percentage)(\.|$)/i)||null,term:textValue(entries,/(^|\.)(semester|term)(\.|$)/i),period:numberValue(entries,/(^|\.)(period)(\.|$)/i)||null,startDate:textValue(entries,/(^|\.)(startDate|startsAt)(\.|$)/i),applicationDeadline:textValue(entries,/(application|admission).*(close|end|last).*date$/i),applicationOpensAt:textValue(entries,/(application|admission).*(open|start).*date$/i),applicationClosesAt:textValue(entries,/(application|admission).*(close|end|last).*date$/i),applicationOpen:false,distance:true,currentOffering:true,verified:true,noPhysicalMeetings:null,url:textValue(entries,/(^|\.)(url|webpage|informationUrl|applicationUrl).*value?$/i)}}
function normalizeResponse(data,subject){const seen=new Set();return eventList(data).map(x=>normalizeEvent(x,subject)).filter(course=>{if(!course)return false;const key=[course.code,course.name,course.university,course.startDate].join('|').toLocaleLowerCase('sv');if(seen.has(key))return false;seen.add(key);return true}).slice(0,60)}
async function schemaBase(){try{const r=await fetch(SUSA_SCHEMA_URL,{headers:{accept:'text/yaml,text/plain'},signal:AbortSignal.timeout(5000)});if(!r.ok)return SUSA_FALLBACK_BASE;const yaml=await r.text();const server=yaml.match(/^\s*-\s*url:\s*["']?([^\s"']+)/m)?.[1];if(!server)return SUSA_FALLBACK_BASE;const base=new URL(server,SUSA_SCHEMA_URL);if(!base.pathname.endsWith('/'))base.pathname+='/';return base.href}catch(_){return SUSA_FALLBACK_BASE}}
async function getJson(url,timeout=12000){const r=await fetch(url,{headers:{accept:'application/json'},signal:AbortSignal.timeout(timeout)});if(!r.ok)throw new Error(`Susa-navet ${r.status}`);return r.json()}
function totalPages(data){const n=Number(data?.totalPages??data?.page?.totalPages??data?.pagination?.totalPages);return Number.isFinite(n)&&n>0?Math.ceil(n):1}
function isActive(resource){if(!resource||String(resource.status||'ACTIVE').toUpperCase()!=='ACTIVE')return false;const expires=resource?.content?.expires;return !expires||!Number.isFinite(Date.parse(expires))||Date.parse(expires)>=Date.now()-86400000}
function subjectTitleTerms(subject){const key=String(subject||'').trim().toLocaleLowerCase('sv');const aliases={'företagsekonomi':['företagsekonomi','business administration'],'psykologi':['psykologi','psychology'],'idrottsvetenskap':['idrottsvetenskap','sport science'],'nationalekonomi':['nationalekonomi','economics'],'statsvetenskap':['statsvetenskap','political science'],'historia':['historia']};return aliases[key]||[key]}
function matchesSubject(info,subject){if(!subject)return true;const key=String(subject).trim().toLocaleLowerCase('sv');const officialCode=UH_SUBJECT_CODES[key];if(officialCode){const subjects=info?.content?.subjects||[];return subjects.some(s=>s?.type==='UH_Subject'&&String(s?.code||'')===officialCode)}const titles=localizedAll(info?.content?.title).map(x=>x.toLocaleLowerCase('sv'));return subjectTitleTerms(subject).some(term=>term&&titles.some(title=>title.includes(term)))}
function hpFromInfo(info){const credits=Number(info?.content?.credits?.credits);const system=String(info?.content?.credits?.system?.code||'').toLocaleLowerCase('sv');if(Number.isFinite(credits)&&credits>0&&(!system||/(hp|ects|credit|poäng|point)/i.test(system)))return credits;const extent=info?.content?.extent||{};const length=Number(extent.length)||0;const unit=String(extent?.unit?.code||'').toLocaleLowerCase('sv');if(!length)return 0;if(/(hp|credit|credits|ects|poäng|points)/i.test(unit))return length;if(/semester/i.test(unit))return length*30;if(/week|veck/i.test(unit))return length*1.5;return 0}
function distanceMeetingState(event){const description=localized(event?.content?.distance?.description);if(!description)return null;if(PHYSICAL_RE.test(description))return false;if(NO_PHYSICAL_RE.test(description))return true;return null}
function norm(v){return String(v??'').trim().toLocaleLowerCase('sv-SE').normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function codeNorm(v){return String(v??'').trim().toUpperCase().replace(/[^A-Z0-9ÅÄÖ]/g,'')}
function courseFromJoined(event,info,provider,subject){const ec=event?.content||{},ic=info?.content||{},pc=provider?.content||{};if(!isActive(event)||!isActive(info)||!isActive(provider))return null;if(!event?.content?.distance)return null;const configuration=String(ic?.configuration?.code||'').toLocaleLowerCase('sv');if(configuration!=='kurs'&&configuration!=='course')return null;if(!matchesSubject(info,subject))return null;const hp=hpFromInfo(info);if(!(hp>0))return null;const name=localized(ic.title);const university=localized(pc.name);if(!name||!university)return null;const applicationUrl=localized(ec?.application?.url)||localized(ic.url);const startDate=String(ec.startDate||ec.start||ec.from||'');const applicationOpensAt=String(ec?.application?.startDate||ec?.application?.opens||'');const applicationClosesAt=String(ec?.application?.endDate||ec?.application?.lastApplicationDate||'');const now=Date.now(),open=Date.parse(applicationOpensAt),close=Date.parse(applicationClosesAt);const educationId=String(ec.education||''),offeringId=String(event?.id||ec.identifier||'');const code=String(ic.code||'');return {source:'skolverket-susa-navet',sourceId:educationId,offeringId,definitionKey:[norm(university),codeNorm(code),'course'].join('|'),offeringKey:['susa',offeringId||educationId,startDate].join('|'),name,code,university,subject,hp,pace:Number(ec?.paceOfStudy?.percentage)||null,term:'',period:null,startDate,applicationDeadline:applicationClosesAt,applicationOpensAt,applicationClosesAt,applicationOpen:Number.isFinite(open)&&Number.isFinite(close)&&now>=open&&now<=close,distance:true,currentOffering:true,verified:true,noPhysicalMeetings:distanceMeetingState(event),url:applicationUrl}}
async function mapLimit(items,limit,worker){const results=new Array(items.length);let next=0;async function run(){while(true){const i=next++;if(i>=items.length)return;try{results[i]=await worker(items[i],i)}catch(_){results[i]=null}}}await Promise.all(Array.from({length:Math.min(limit,items.length)},run));return results}
async function fetchAllEvents(base){const size=2000;const firstUrl=new URL('educationEvents',base);firstUrl.searchParams.set('schoolType','HS');firstUrl.searchParams.set('page','0');firstUrl.searchParams.set('size',String(size));const first=await getJson(firstUrl,15000);const pages=Math.min(totalPages(first),80);if(pages<=1)return eventList(first);const rest=await mapLimit(Array.from({length:pages-1},(_,i)=>i+1),5,async page=>{const u=new URL('educationEvents',base);u.searchParams.set('schoolType','HS');u.searchParams.set('page',String(page));u.searchParams.set('size',String(size));return getJson(u,15000)});return [first,...rest.filter(Boolean)].flatMap(eventList)}
async function fetchProviders(base){const u=new URL('educationProviders',base);u.searchParams.set('schoolType','HS');u.searchParams.set('page','0');u.searchParams.set('size','2000');const data=await getJson(u,12000);const map=new Map();for(const p of providerList(data)){const id=String(p?.id||p?.content?.identifier||'');if(id)map.set(id,p)}return map}
async function fetchSusaCourses(subject){const base=await schemaBase();const [allEvents,providers]=await Promise.all([fetchAllEvents(base),fetchProviders(base)]);const events=allEvents.filter(e=>isActive(e)&&e?.content?.distance&&e?.content?.education&&e?.content?.providers?.[0]);const unique=[];const seenEvent=new Set();for(const e of events){const id=String(e.id||e?.content?.identifier||[e?.content?.education,e?.content?.start].join('|'));if(id&&!seenEvent.has(id)){seenEvent.add(id);unique.push(e)}}const infoCache=new Map();const hydrated=await mapLimit(unique,32,async event=>{const educationId=event.content.education,providerId=event.content.providers[0],provider=providers.get(providerId);if(!provider)return null;if(!infoCache.has(educationId))infoCache.set(educationId,getJson(new URL(`educationInfos/${encodeURIComponent(educationId)}`,base),9000).catch(()=>null));const info=await infoCache.get(educationId);return info?courseFromJoined(event,info,provider,subject):null});const seen=new Set();return hydrated.filter(Boolean).filter(course=>{if(seen.has(course.offeringKey))return false;seen.add(course.offeringKey);return true}).sort((a,b)=>String(a.startDate).localeCompare(String(b.startDate))||String(a.university).localeCompare(String(b.university),'sv')).slice(0,60)}
export {eventList,explicitDistance,normalizeEvent,normalizeResponse};
export default async function handler(req,res){res.setHeader('Cache-Control','s-maxage=3600, stale-while-revalidate=86400');const subject=String(req.query?.subject||'').trim();try{let courses;if(process.env.DISTANCE_COURSE_FEED_URL){const u=new URL(process.env.DISTANCE_COURSE_FEED_URL);if(subject)u.searchParams.set('subject',subject);u.searchParams.set('kind',String(req.query?.kind||'candidate'));courses=normalizeResponse(await getJson(u,10000),subject)}else courses=await fetchSusaCourses(subject);return res.status(200).json({courses,identityPolicy:{definition:'university + code + type',offering:'Susa event id + start date',merge:'discovery only; never replace degree/program rules'},updated:new Date().toISOString(),source:process.env.DISTANCE_COURSE_FEED_URL?'configured-feed':'skolverket-susa-navet'})}catch(error){console.error('distance-courses',error);return res.status(200).json({courses:[],updated:new Date().toISOString(),source:'skolverket-susa-navet',temporarilyUnavailable:true})}}
