const FALLBACK=[
['Företagsekonomi','Göteborgs universitet','Ekonomie kandidatprogram'],['Företagsekonomi','Lunds universitet','Ekonomie kandidatprogram'],['Företagsekonomi','Stockholms universitet','Kandidatprogram i företagsekonomi'],['Företagsekonomi','Uppsala universitet','Ekonomie kandidatprogram'],['Företagsekonomi','Umeå universitet','Ekonomie kandidatprogram'],['Psykologi','Göteborgs universitet','Kandidatprogram i psykologi'],['Psykologi','Lunds universitet','Kandidatprogram i psykologi'],['Psykologi','Stockholms universitet','Kandidatprogram i psykologi'],['Idrottsvetenskap','Göteborgs universitet','Idrottsvetenskapligt program'],['Idrottsvetenskap','Malmö universitet','Idrottsvetenskapligt program'],['Nationalekonomi','Göteborgs universitet','Ekonomie kandidatprogram'],['Nationalekonomi','Lunds universitet','Ekonomie kandidatprogram'],['Statsvetenskap','Göteborgs universitet','Statsvetarprogrammet'],['Statsvetenskap','Lunds universitet','Politices kandidatprogrammet'],['Folkhälsovetenskap','Göteborgs universitet','Kandidatprogram i folkhälsovetenskap']
].map(([subject,university,programName])=>({subject,university,programName,source:'studielots-fallback'}));
const SIX_HOURS=21600000,FULL_REFRESH=7*86400000,SUSA_SCHEMA_URL='https://api.skolverket.se/susa-navet/susa-navet-emil3.yaml',SUSA_FALLBACK_BASE='https://api.skolverket.se/susa-navet/emil3/';
let cache={rows:FALLBACK,updated:0,lastFull:0,lastIncremental:0,source:'fallback'};
const clean=v=>String(v??'').trim(),norm=v=>clean(v).toLocaleLowerCase('sv-SE').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const localized=value=>{const rows=value?.strings||value?.urls||[];const swe=rows.find(x=>String(x?.lang||'').toLowerCase()==='swe');return clean((swe||rows[0])?.value)};
const list=(data,keys)=>{if(Array.isArray(data))return data;for(const key of keys)if(Array.isArray(data?.[key]))return data[key];return[]},infoList=d=>list(d,['educationInfos','educationInfo','items','content','results','data']),providerList=d=>list(d,['educationProviders','providers','items','content','results','data']),eventList=d=>list(d,['educationEvents','events','items','content','results','data']);
const isActive=r=>{if(!r||String(r.status||'ACTIVE').toUpperCase()!=='ACTIVE')return false;const expires=r?.content?.expires;return !expires||!Number.isFinite(Date.parse(expires))||Date.parse(expires)>=Date.now()-86400000},isProgram=info=>['program','programme','programmeutbildning'].includes(norm(info?.content?.configuration?.code));
function scalarEntries(value,path='',out=[]){if(value==null)return out;if(Array.isArray(value))value.forEach((x,i)=>scalarEntries(x,`${path}[${i}]`,out));else if(typeof value==='object')Object.entries(value).forEach(([k,x])=>scalarEntries(x,path?`${path}.${k}`:k,out));else if(['string','number','boolean'].includes(typeof value))out.push({path,value});return out}
function providerId(info){const c=info?.content||{},direct=clean(c.provider||c.providers?.[0]||c.organizer||c.educationProvider);return direct||clean(scalarEntries(c).find(x=>/(provider|organizer|educationProvider)(\[0\])?$/i.test(x.path))?.value)}
function hp(info){const credits=Number(info?.content?.credits?.credits);if(Number.isFinite(credits)&&credits>0)return credits;const e=info?.content?.extent||{},n=Number(e.length),unit=norm(e?.unit?.code);if(!Number.isFinite(n)||n<=0)return null;if(/hp|credit|ects|poang|point/.test(unit))return n;if(/semester/.test(unit))return n*30;return null}
async function schemaBase(){try{const r=await fetch(SUSA_SCHEMA_URL,{headers:{accept:'text/yaml,text/plain'},signal:AbortSignal.timeout(3500)});if(!r.ok)return SUSA_FALLBACK_BASE;const yaml=await r.text(),server=yaml.match(/^\s*-\s*url:\s*["']?([^\s"']+)/m)?.[1];if(!server)return SUSA_FALLBACK_BASE;const base=new URL(server,SUSA_SCHEMA_URL);if(!base.pathname.endsWith('/'))base.pathname+='/';return base.href}catch(_){return SUSA_FALLBACK_BASE}}
async function getJson(url,timeout=12000){const r=await fetch(url,{headers:{accept:'application/json'},signal:AbortSignal.timeout(timeout)});if(!r.ok)throw Error(`Susa-navet ${r.status}`);return r.json()}
function totalPages(d){const n=Number(d?.totalPages??d?.page?.totalPages??d?.pagination?.totalPages);return Number.isFinite(n)&&n>0?Math.ceil(n):1}
async function collection(base,path,listFn,{updatedSince='',maxPages=80}={}){const size=2000,make=page=>{const u=new URL(path,base);u.searchParams.set('schoolType','HS');u.searchParams.set('page',String(page));u.searchParams.set('size',String(size));if(updatedSince)u.searchParams.set('updatedSince',updatedSince);return u};const first=await getJson(make(0)),pages=Math.min(totalPages(first),maxPages),out=[...listFn(first)];for(let p=1;p<pages;p+=8){const batch=await Promise.all(Array.from({length:Math.min(8,pages-p)},(_,i)=>getJson(make(p+i)).catch(()=>null)));for(const d of batch)if(d)out.push(...listFn(d))}return out}
function subjectLabel(info){const subjects=info?.content?.subjects||[],uh=subjects.find(s=>s?.type==='UH_Subject'),name=localized(uh?.name)||clean(uh?.name)||localized(info?.content?.subject);return name||'Övrigt'}
function key(x){return norm(`${x.sourceId||x.programCode||''}|${x.university}|${x.programName}`)}
async function collectAll(updatedSince=''){const base=await schemaBase(),opts={updatedSince},infos=(await collection(base,'educationInfos',infoList,opts)).filter(x=>isActive(x)&&isProgram(x)),ids=new Set(infos.map(x=>clean(x?.id||x?.content?.identifier)).filter(Boolean)),providersByEducation=new Map(),neededProviders=new Set(infos.map(providerId).filter(Boolean));if(ids.size){const events=await collection(base,'educationEvents',eventList,opts);for(const e of events){if(!isActive(e))continue;const eid=clean(e?.content?.education);if(!ids.has(eid))continue;const pid=clean(e?.content?.providers?.[0]);if(pid){providersByEducation.set(eid,pid);neededProviders.add(pid)}}}const providers=await collection(base,'educationProviders',providerList),byId=new Map();for(const p of providers){const id=clean(p?.id||p?.content?.identifier);if(id&&neededProviders.has(id))byId.set(id,p)}const rows=[];for(const info of infos){const id=clean(info?.id||info?.content?.identifier),pid=providerId(info)||providersByEducation.get(id),university=localized(byId.get(pid)?.content?.name),programName=localized(info?.content?.title);if(!university||!programName)continue;rows.push({subject:subjectLabel(info),university,programName,programCode:clean(info?.content?.code),programHp:hp(info),sourceId:id,source:'skolverket-susa-navet'})}const map=new Map();for(const x of rows)map.set(key(x),x);return[...map.values()]}
function merge(base,changes){const map=new Map(base.map(x=>[key(x),x]));for(const x of changes){const k=key(x);if(!x.university||!x.programName)continue;if(x.deleted===true||x.expired===true)map.delete(k);else map.set(k,x)}return[...map.values()]}
async function refresh(){const now=Date.now(),needFull=!cache.lastFull||now-cache.lastFull>FULL_REFRESH;if(needFull){const live=await collectAll();if(live.length){cache={rows:live,updated:now,lastFull:now,lastIncremental:now,source:'skolverket-susa-navet'};return cache}return cache}const since=new Date(cache.lastIncremental||cache.updated||cache.lastFull).toISOString(),changes=await collectAll(since);cache={...cache,rows:changes.length?merge(cache.rows,changes):cache.rows,updated:now,lastIncremental:now};return cache}
export default async function handler(req,res){res.setHeader('Cache-Control','s-maxage=21600, stale-while-revalidate=86400');try{if(Date.now()-cache.updated>SIX_HOURS)await refresh();const subject=norm(req.query?.subject),q=norm(req.query?.q),university=norm(req.query?.university);let rows=cache.rows;if(subject)rows=rows.filter(x=>norm(x.subject)===subject);if(university)rows=rows.filter(x=>norm(x.university).includes(university));if(q)rows=rows.filter(x=>norm(`${x.programName} ${x.university} ${x.subject} ${x.programCode}`).includes(q));return res.status(200).json({programs:rows,source:cache.source,updated:cache.updated?new Date(cache.updated).toISOString():null,lastFull:cache.lastFull?new Date(cache.lastFull).toISOString():null,lastIncremental:cache.lastIncremental?new Date(cache.lastIncremental).toISOString():null,fallback:cache.source==='fallback'})}catch(error){console.error('program-index',error);return res.status(200).json({programs:cache.rows?.length?cache.rows:FALLBACK,source:cache.source||'fallback',fallback:cache.source==='fallback'})}}
