const FALLBACK=[
['Företagsekonomi','Göteborgs universitet','Ekonomie kandidatprogram'],['Företagsekonomi','Lunds universitet','Ekonomie kandidatprogram'],['Företagsekonomi','Stockholms universitet','Kandidatprogram i företagsekonomi'],['Företagsekonomi','Uppsala universitet','Ekonomie kandidatprogram'],['Företagsekonomi','Umeå universitet','Ekonomie kandidatprogram'],['Psykologi','Göteborgs universitet','Kandidatprogram i psykologi'],['Psykologi','Lunds universitet','Kandidatprogram i psykologi'],['Psykologi','Stockholms universitet','Kandidatprogram i psykologi'],['Idrottsvetenskap','Göteborgs universitet','Idrottsvetenskapligt program'],['Idrottsvetenskap','Malmö universitet','Idrottsvetenskapligt program'],['Nationalekonomi','Göteborgs universitet','Ekonomie kandidatprogram'],['Nationalekonomi','Lunds universitet','Ekonomie kandidatprogram'],['Statsvetenskap','Göteborgs universitet','Statsvetarprogrammet'],['Statsvetenskap','Lunds universitet','Politices kandidatprogrammet'],['Folkhälsovetenskap','Göteborgs universitet','Kandidatprogram i folkhälsovetenskap']
].map(([subject,university,programName])=>({subject,university,programName,source:'studielots-fallback'}));
const SUBJECTS=['Företagsekonomi','Psykologi','Idrottsvetenskap','Nationalekonomi','Statsvetenskap','Pedagogik','Folkhälsovetenskap','Arbetsvetenskap'];
let cache={rows:FALLBACK,updated:0,source:'fallback'};
const norm=v=>String(v??'').toLocaleLowerCase('sv-SE').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim();
async function one(subject){const origin=process.env.VERCEL_URL?`https://${process.env.VERCEL_URL}`:'';if(!origin)return[];const r=await fetch(`${origin}/api/university-paths?${new URLSearchParams({subject,kind:'candidate'})}`,{signal:AbortSignal.timeout(12000)});if(!r.ok)return[];const d=await r.json();return(d.universities||[]).map(x=>({...x,subject}))}
async function refresh(){const batches=await Promise.all(SUBJECTS.map(async s=>{try{return await one(s)}catch(_){return[]}}));const seen=new Set(),live=batches.flat().filter(x=>{const k=norm(`${x.subject}|${x.university}|${x.programName}`);if(!x.university||!x.programName||seen.has(k))return false;seen.add(k);return true});if(live.length){cache={rows:live,updated:Date.now(),source:'skolverket-susa-navet'};return cache}return cache}
export default async function handler(req,res){res.setHeader('Cache-Control','s-maxage=21600, stale-while-revalidate=86400');try{if(Date.now()-cache.updated>21600000)await refresh();const subject=norm(req.query?.subject),q=norm(req.query?.q);let rows=cache.rows;if(subject)rows=rows.filter(x=>norm(x.subject)===subject);if(q)rows=rows.filter(x=>norm(`${x.programName} ${x.university} ${x.subject}`).includes(q));return res.status(200).json({programs:rows,source:cache.source,updated:cache.updated?new Date(cache.updated).toISOString():null,fallback:cache.source==='fallback'})}catch(error){console.error('program-index',error);return res.status(200).json({programs:FALLBACK,source:'fallback',fallback:true})}}
