const FALLBACK=[
['Företagsekonomi','Göteborgs universitet','Ekonomie kandidatprogram'],['Företagsekonomi','Lunds universitet','Ekonomie kandidatprogram'],['Företagsekonomi','Stockholms universitet','Kandidatprogram i företagsekonomi'],['Företagsekonomi','Uppsala universitet','Ekonomie kandidatprogram'],['Företagsekonomi','Umeå universitet','Ekonomie kandidatprogram'],['Psykologi','Göteborgs universitet','Kandidatprogram i psykologi'],['Psykologi','Lunds universitet','Kandidatprogram i psykologi'],['Psykologi','Stockholms universitet','Kandidatprogram i psykologi'],['Idrottsvetenskap','Göteborgs universitet','Idrottsvetenskapligt program'],['Idrottsvetenskap','Malmö universitet','Idrottsvetenskapligt program'],['Nationalekonomi','Göteborgs universitet','Ekonomie kandidatprogram'],['Nationalekonomi','Lunds universitet','Ekonomie kandidatprogram'],['Statsvetenskap','Göteborgs universitet','Statsvetarprogrammet'],['Statsvetenskap','Lunds universitet','Politices kandidatprogrammet'],['Folkhälsovetenskap','Göteborgs universitet','Kandidatprogram i folkhälsovetenskap']
].map(([subject,university,programName])=>({subject,university,programName,source:'studielots-fallback'}));
const SUBJECTS=['Företagsekonomi','Psykologi','Idrottsvetenskap','Nationalekonomi','Statsvetenskap','Pedagogik','Folkhälsovetenskap','Arbetsvetenskap'];
const SIX_HOURS=21600000,FULL_REFRESH=7*86400000;
let cache={rows:FALLBACK,updated:0,lastFull:0,lastIncremental:0,source:'fallback'};
const norm=v=>String(v??'').toLocaleLowerCase('sv-SE').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim();
const key=x=>norm(`${x.subject}|${x.university}|${x.programName}`);
async function one(subject,updatedSince=''){const origin=process.env.VERCEL_URL?`https://${process.env.VERCEL_URL}`:'';if(!origin)return[];const params={subject,kind:'candidate'};if(updatedSince)params.updatedSince=updatedSince;const r=await fetch(`${origin}/api/university-paths?${new URLSearchParams(params)}`,{signal:AbortSignal.timeout(12000)});if(!r.ok)return[];const d=await r.json();return(d.universities||[]).map(x=>({...x,subject}))}
function merge(base,changes){const map=new Map(base.map(x=>[key(x),x]));for(const x of changes){const k=key(x);if(!x.university||!x.programName)continue;if(x.deleted===true||x.expired===true)map.delete(k);else map.set(k,x)}return[...map.values()]}
async function collect(updatedSince=''){const batches=await Promise.all(SUBJECTS.map(async s=>{try{return await one(s,updatedSince)}catch(_){return[]}}));const seen=new Set();return batches.flat().filter(x=>{const k=key(x);if(!x.university||!x.programName||seen.has(k))return false;seen.add(k);return true})}
async function refresh(){const now=Date.now(),needFull=!cache.lastFull||now-cache.lastFull>FULL_REFRESH;if(needFull){const live=await collect();if(live.length){cache={...cache,rows:live,updated:now,lastFull:now,lastIncremental:now,source:'skolverket-susa-navet'};return cache}return cache}const since=new Date(cache.lastIncremental||cache.updated||cache.lastFull).toISOString();const changes=await collect(since);cache={...cache,rows:changes.length?merge(cache.rows,changes):cache.rows,updated:now,lastIncremental:now,source:cache.source==='fallback'?'fallback':'skolverket-susa-navet'};return cache}
export default async function handler(req,res){res.setHeader('Cache-Control','s-maxage=21600, stale-while-revalidate=86400');try{if(Date.now()-cache.updated>SIX_HOURS)await refresh();const subject=norm(req.query?.subject),q=norm(req.query?.q);let rows=cache.rows;if(subject)rows=rows.filter(x=>norm(x.subject)===subject);if(q)rows=rows.filter(x=>norm(`${x.programName} ${x.university} ${x.subject}`).includes(q));return res.status(200).json({programs:rows,source:cache.source,updated:cache.updated?new Date(cache.updated).toISOString():null,lastFull:cache.lastFull?new Date(cache.lastFull).toISOString():null,lastIncremental:cache.lastIncremental?new Date(cache.lastIncremental).toISOString():null,fallback:cache.source==='fallback'})}catch(error){console.error('program-index',error);return res.status(200).json({programs:cache.rows?.length?cache.rows:FALLBACK,source:cache.source||'fallback',fallback:cache.source==='fallback'})}}
