const SUSA_SCHEMA_URL='https://api.skolverket.se/susa-navet/susa-navet-emil3.yaml';
const SUSA_FALLBACK_BASE='https://api.skolverket.se/susa-navet/emil3/';
const UH_SUBJECT_CODES={'företagsekonomi':'616','psykologi':'420','idrottsvetenskap':'434','nationalekonomi':'571','statsvetenskap':'482'};
const clean=v=>String(v??'').trim();
const norm=v=>clean(v).toLocaleLowerCase('sv-SE').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const localized=value=>{const rows=value?.strings||value?.urls||[];const swe=rows.find(x=>String(x?.lang||'').toLowerCase()==='swe');return clean((swe||rows[0])?.value)};
const list=(data,keys)=>{if(Array.isArray(data))return data;for(const key of keys)if(Array.isArray(data?.[key]))return data[key];return[]};
const infoList=data=>list(data,['educationInfos','educationInfo','items','content','results','data']);
const providerList=data=>list(data,['educationProviders','providers','items','content','results','data']);
const eventList=data=>list(data,['educationEvents','events','items','content','results','data']);
const isActive=r=>{if(!r||String(r.status||'ACTIVE').toUpperCase()!=='ACTIVE')return false;const expires=r?.content?.expires;return !expires||!Number.isFinite(Date.parse(expires))||Date.parse(expires)>=Date.now()-86400000};
async function schemaBase(){try{const r=await fetch(SUSA_SCHEMA_URL,{headers:{accept:'text/yaml,text/plain'},signal:AbortSignal.timeout(5000)});if(!r.ok)return SUSA_FALLBACK_BASE;const yaml=await r.text();const server=yaml.match(/^\s*-\s*url:\s*["']?([^\s"']+)/m)?.[1];if(!server)return SUSA_FALLBACK_BASE;const base=new URL(server,SUSA_SCHEMA_URL);if(!base.pathname.endsWith('/'))base.pathname+='/';return base.href}catch(_){return SUSA_FALLBACK_BASE}}
async function getJson(url,timeout=15000){const r=await fetch(url,{headers:{accept:'application/json'},signal:AbortSignal.timeout(timeout)});if(!r.ok)throw new Error(`Susa-navet ${r.status}`);return r.json()}
function totalPages(data){const n=Number(data?.totalPages??data?.page?.totalPages??data?.pagination?.totalPages);return Number.isFinite(n)&&n>0?Math.ceil(n):1}
async function mapLimit(items,limit,worker){const results=new Array(items.length);let next=0;async function run(){while(true){const i=next++;if(i>=items.length)return;try{results[i]=await worker(items[i],i)}catch(_){results[i]=null}}}await Promise.all(Array.from({length:Math.min(limit,items.length)},run));return results}
async function fetchCollection(base,path,listFn){const size=2000;const firstUrl=new URL(path,base);firstUrl.searchParams.set('schoolType','HS');firstUrl.searchParams.set('page','0');firstUrl.searchParams.set('size',String(size));const first=await getJson(firstUrl);const pages=Math.min(totalPages(first),80);if(pages<=1)return listFn(first);const rest=await mapLimit(Array.from({length:pages-1},(_,i)=>i+1),8,async page=>{const u=new URL(path,base);u.searchParams.set('schoolType','HS');u.searchParams.set('page',String(page));u.searchParams.set('size',String(size));return getJson(u)});return[first,...rest.filter(Boolean)].flatMap(listFn)}
function isProgram(info){const code=norm(info?.content?.configuration?.code);return ['program','programme','programmeutbildning'].includes(code)}
function scalarEntries(value,path='',out=[]){if(value==null)return out;if(Array.isArray(value))value.forEach((x,i)=>scalarEntries(x,`${path}[${i}]`,out));else if(typeof value==='object')Object.entries(value).forEach(([k,x])=>scalarEntries(x,path?`${path}.${k}`:k,out));else if(['string','number','boolean'].includes(typeof value))out.push({path,value});return out}
function providerIdFromInfo(info){const c=info?.content||{};const direct=clean(c.provider||c.providers?.[0]||c.organizer||c.educationProvider);if(direct)return direct;return clean(scalarEntries(c).find(x=>/(provider|organizer|educationProvider)(\[0\])?$/i.test(x.path))?.value)}
function subjectTerms(subject){const key=norm(subject);const aliases={'företagsekonomi':['företagsekonomi','business administration'],'psykologi':['psykologi','psychology'],'idrottsvetenskap':['idrottsvetenskap','sport science'],'nationalekonomi':['nationalekonomi','economics'],'statsvetenskap':['statsvetenskap','political science'],'pedagogik':['pedagogik','education'],'folkhälsovetenskap':['folkhälsovetenskap','public health'],'arbetsvetenskap':['arbetsvetenskap','work science']};return aliases[key]||[key]}
function subjectMatch(info,subject){const key=norm(subject);if(!key)return false;const subjects=info?.content?.subjects||[],official=UH_SUBJECT_CODES[key];const officialHit=official&&subjects.some(s=>s?.type==='UH_Subject'&&String(s?.code||'')===official);const title=norm(localized(info?.content?.title));const titleHit=subjectTerms(subject).some(t=>t&&title.includes(norm(t)));return{match:Boolean(officialHit||titleHit),evidence:officialHit?'official-subject-code':titleHit?'programme-title':''}}
function levelText(info){return scalarEntries(info).filter(x=>/(level|progression|cycle|nivå|niva)/i.test(x.path)).map(x=>String(x.value)).join(' ')}
function matchesKind(info,kind){const k=norm(kind||'candidate'),title=localized(info?.content?.title),meta=levelText(info),advanced=/(master|magister|avancerad nivå|advanced level|second cycle|\bA1[NFE]\b|\bA2E\b)/i.test(title+' '+meta);if(k==='candidate')return !advanced;if(['master','magister','advanced'].includes(k))return advanced;return true}
function providerMaps(providers,events){const byId=new Map(),byEducation=new Map();for(const p of providers){const id=clean(p?.id||p?.content?.identifier);if(id)byId.set(id,p)}for(const e of events){if(!isActive(e))continue;const education=clean(e?.content?.education),pid=clean(e?.content?.providers?.[0]);if(education&&pid&&!byEducation.has(education))byEducation.set(education,pid)}return{byId,byEducation}}
async function discover(subject,kind){const base=await schemaBase();const [infos,providers,events]=await Promise.all([fetchCollection(base,'educationInfos',infoList),fetchCollection(base,'educationProviders',providerList),fetchCollection(base,'educationEvents',eventList)]);const maps=providerMaps(providers,events),out=[],seen=new Set();for(const info of infos){if(!isActive(info)||!isProgram(info)||!matchesKind(info,kind))continue;const hit=subjectMatch(info,subject);if(!hit.match)continue;const id=clean(info?.id||info?.content?.identifier),pid=providerIdFromInfo(info)||maps.byEducation.get(id),provider=maps.byId.get(pid),university=localized(provider?.content?.name),programName=localized(info?.content?.title);if(!university||!programName)continue;const key=norm(university);if(seen.has(key))continue;seen.add(key);out.push({university,programName,programCode:clean(info?.content?.code),sourceId:id,evidence:hit.evidence,verifiedDegreeRule:false,source:'skolverket-susa-navet'})}return out.sort((a,b)=>a.university.localeCompare(b.university,'sv')).slice(0,50)}
export default async function handler(req,res){res.setHeader('Cache-Control','s-maxage=21600, stale-while-revalidate=86400');const subject=clean(req.query?.subject),kind=clean(req.query?.kind||'candidate');if(!subject)return res.status(400).json({error:'subject is required'});try{const universities=await discover(subject,kind);return res.status(200).json({subject,kind,universities,source:'skolverket-susa-navet',policy:'Discovery only. Susa programme evidence may expand the institution list but never replaces a verified local degree rule.',updated:new Date().toISOString()})}catch(error){console.error('university-paths',error);return res.status(200).json({subject,kind,universities:[],source:'skolverket-susa-navet',temporarilyUnavailable:true,updated:new Date().toISOString()})}}
